import importlib.util
import json
import tempfile
import unittest
import urllib.error
from pathlib import Path
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "build_project_integrity_feed.py"
SPEC = importlib.util.spec_from_file_location("project_integrity_feed_contract", SCRIPT)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(MODULE)


class ProjectIntegrityFeedContractTests(unittest.TestCase):
    def report(self):
        return {
            "schema_version": 1,
            "generated_at": "2026-07-25T12:00:00Z",
            "revision": "abcdef123456",
            "result": "clean",
            "counts": {
                "errors": 0,
                "warnings": 0,
                "findings": 0,
                "issue_pages": 64,
                "proposal_pages": 41,
            },
            "scope": ["repository identity", "Project consistency"],
            "findings": [],
            "duration_seconds": 1.5,
        }

    def test_feed_exposes_uniform_contract_and_bounded_history(self):
        feed = MODULE.build_feed(
            self.report(),
            {
                "history": [
                    {
                        "generated_at": "2026-07-24T12:00:00Z",
                        "revision": "prior",
                        "result": "clean",
                        "counts": {"findings": 0},
                    }
                ]
            },
            2,
        )
        self.assertEqual(feed["schema_version"], 2)
        self.assertTrue(feed["generation_id"].startswith("project-integrity-"))
        self.assertEqual(feed["source_revision"], "abcdef123456")
        self.assertEqual(feed["expected_count"], 2)
        self.assertEqual(feed["actual_count"], 2)
        self.assertTrue(feed["completeness"]["complete"])
        self.assertEqual(len(feed["history"]), 2)

    def test_invalid_existing_history_fails_closed(self):
        with self.assertRaisesRegex(RuntimeError, "history contract"):
            MODULE.build_feed(self.report(), {"history": "not-an-array"}, 3)
        with self.assertRaisesRegex(RuntimeError, "non-object"):
            MODULE.build_feed(self.report(), {"history": ["invalid"]}, 3)

    def test_network_failure_does_not_erase_integrity_history(self):
        url = (
            "https://raw.githubusercontent.com/Thorncrag/ARRP/"
            "project-console-data/integrity.json"
        )
        with mock.patch.object(
            MODULE.urllib.request,
            "urlopen",
            side_effect=urllib.error.URLError("offline"),
        ):
            with self.assertRaisesRegex(RuntimeError, "refusing to replace"):
                MODULE.existing_feed(url)

    def test_integrity_report_rejects_paths_outside_trusted_roots(self):
        with self.assertRaisesRegex(ValueError, "repository or system temporary"):
            MODULE.read_json(Path("/etc/hosts"))

    def test_integrity_report_hashes_trusted_temporary_input(self):
        with tempfile.TemporaryDirectory() as directory:
            report_path = Path(directory) / "integrity-report.json"
            report_path.write_text("{}\n", encoding="utf-8")
            feed = MODULE.build_feed(
                self.report(),
                {},
                1,
                report_path=report_path,
            )
        self.assertEqual(
            list(feed["source_hashes"]),
            ["integrity-report.json"],
        )

    def test_local_console_domain_retains_integrity_history(self):
        retained = {
            "history": [
                {
                    "generated_at": "2026-07-24T12:00:00Z",
                    "revision": "prior",
                    "result": "clean",
                    "counts": {"findings": 0},
                }
            ]
        }
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "integrity.js"
            path.write_text(
                "/* Generated by scripts/build_horizon_review_console.py. */\n"
                "window.ARRP_HORIZON_REVIEW_DATA="
                "window.ARRP_HORIZON_REVIEW_DATA||{};\n"
                "Object.assign(window.ARRP_HORIZON_REVIEW_DATA,"
                + json.dumps({"integrity": retained})
                + ");\n",
                encoding="utf-8",
            )
            self.assertEqual(
                MODULE.existing_feed_file(path),
                retained,
            )

    def test_private_operations_projection_retains_owner_local_history(self):
        retained = {
            "history": [
                {
                    "generated_at": "2026-07-24T12:00:00Z",
                    "revision": "prior",
                    "result": "findings",
                    "counts": {"findings": 2},
                }
            ]
        }
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "private-operations.js"
            path.write_text(
                "/* Private local projection; never commit or publish. */\n"
                "window.ARRP_PRIVATE_OPERATIONS="
                + json.dumps({"integrity": retained})
                + ";\n",
                encoding="utf-8",
            )
            self.assertEqual(MODULE.existing_feed_file(path), retained)


if __name__ == "__main__":
    unittest.main()
