import csv
import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "research"


def read_csv(name: str) -> list[dict[str, str]]:
    with (RESEARCH / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


class HorizonIntakeTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.catalog = read_csv("trump-administration-legal-review-catalog.csv")
        cls.routing = read_csv("trump-administration-evidence-routing.csv")
        cls.existing_issue_integration = read_csv("existing-issue-evidence-integration.csv")
        cls.litigation_monitoring = read_csv("trump-administration-litigation-monitoring.csv")
        cls.source_universe = read_csv("trump-administration-source-universe.csv")
        cls.media_intake = read_csv("trump-administration-media-review-intake.csv")
        cls.candidates = read_csv("trump-administration-preliminary-candidates.csv")
        with (ROOT / "inventory" / "sources.csv").open(newline="", encoding="utf-8") as handle:
            cls.sources = list(csv.DictReader(handle))
        with (ROOT / "inventory" / "github_issue_registry.csv").open(newline="", encoding="utf-8") as handle:
            cls.issue_registry = list(csv.DictReader(handle))
        bundle = (RESEARCH / "horizon-review-console" / "catalog-data.js").read_text(encoding="utf-8")
        prefix = "/* Generated by scripts/build_horizon_review_console.py. */\nwindow.ARRP_HORIZON_REVIEW_DATA="
        cls.console = json.loads(bundle.removeprefix(prefix).removesuffix(";\n"))
        participation_bundle = (ROOT / "participate" / "intake-data.js").read_text(encoding="utf-8")
        participation_prefix = "/* Generated by scripts/build_horizon_review_console.py. */\nwindow.ARRP_PARTICIPATION_DATA="
        cls.participation = json.loads(
            participation_bundle.removeprefix(participation_prefix).removesuffix(";\n")
        )

    def test_every_catalog_record_has_one_routing_record(self) -> None:
        catalog_ids = [row["catalog_id"] for row in self.catalog]
        routing_ids = [row["catalog_id"] for row in self.routing]
        self.assertEqual(len(catalog_ids), len(set(catalog_ids)))
        self.assertCountEqual(catalog_ids, routing_ids)

    def test_intake_level_review_has_no_pending_records(self) -> None:
        self.assertFalse(any(row["review_status"].endswith("pending") for row in self.routing))
        self.assertFalse(any(row["disposition"] == "agent-review-needed" for row in self.routing))

    def test_routes_use_current_record_identifiers(self) -> None:
        routes = {
            route.strip()
            for row in self.routing
            for route in row["integration_routes"].split(";")
            if route.strip()
        }
        self.assertFalse(any(route.startswith("A-") for route in routes))

    def test_console_contains_only_known_preliminary_candidates(self) -> None:
        candidate_ids = {row["candidate_id"] for row in self.candidates}
        active_candidate_ids = {
            row["candidate_id"]
            for row in self.candidates
            if row["review_status"] == "preliminary-candidate"
        }
        routed_candidate_ids = {row["candidate_id"] for row in self.routing if row["candidate_id"]}
        console_ids = {row["id"] for row in self.console["records"]}
        self.assertTrue(routed_candidate_ids <= candidate_ids)
        self.assertEqual(console_ids, active_candidate_ids)
        self.assertTrue(all(row["kind"] == "preliminary_candidate" for row in self.console["records"]))

    def test_existing_issue_integration_queue_is_distinct_and_reconciled(self) -> None:
        queued_ids = [
            catalog_id.strip()
            for row in self.existing_issue_integration
            for catalog_id in row["catalog_id"].split(";")
            if catalog_id.strip()
        ]
        active_ids = {row["catalog_id"] for row in self.catalog}
        source_ids = {row["Source ID"] for row in self.sources}
        self.assertGreaterEqual(len(queued_ids), 2)
        self.assertTrue({"TAC-IPI1-005", "TAC-IPI1-170"} <= set(queued_ids))
        self.assertEqual(len(queued_ids), len(set(queued_ids)))
        self.assertFalse(set(queued_ids) & active_ids)
        for row in self.existing_issue_integration:
            canonical_ids = {
                source_id.strip()
                for source_id in row["canonical_source_ids"].split(";")
                if source_id.strip()
            }
            self.assertTrue(canonical_ids)
            self.assertTrue(canonical_ids <= source_ids)
        self.assertEqual(self.console["existing_issue_queue"], len(self.existing_issue_integration))

    def test_console_dashboard_reconciles_completed_and_active_work(self) -> None:
        adjudication = self.console["adjudication"]
        self.assertEqual(adjudication["baseline_records"], 1322)
        self.assertEqual(
            adjudication["baseline_records"],
            adjudication["priority_records"] + adjudication["records"],
        )
        self.assertEqual(adjudication["records"], 1266)
        self.assertEqual(
            adjudication["records"],
            adjudication["integration_records"]
            + adjudication["monitoring_records"]
            + adjudication["redundant_records"]
            + adjudication["excluded_records"],
        )
        self.assertEqual(
            self.console["litigation_monitoring_queue"],
            len(self.litigation_monitoring) + 1,
        )
        self.assertEqual(
            len(self.console["integration_records"]),
            len(self.existing_issue_integration),
        )
        self.assertEqual(
            len(self.console["monitoring_records"]),
            len(self.litigation_monitoring) + 1,
        )
        self.assertIn("MEDIA-024", {row["id"] for row in self.console["monitoring_records"]})
        self.assertTrue(all(row["links"] for row in self.console["monitoring_records"]))
        self.assertEqual(
            len(self.console["source_universe_records"]),
            len(self.source_universe),
        )
        self.assertEqual(
            len(self.console["media_records"]),
            len(self.media_intake),
        )
        source_queue = self.console["source_queue_records"]
        self.assertEqual(self.console["source_queue_count"], 206)
        self.assertEqual(
            {kind: sum(row["record_kind"] == kind for row in source_queue) for kind in {"integration", "media", "source"}},
            {"integration": 162, "media": 31, "source": 13},
        )
        self.assertFalse(
            any(
                row.get("stage") in {"Already incorporated", "Monitor through an existing Horizon record"}
                for row in source_queue
            )
        )
        self.assertTrue(
            all(
                row["owner"] == "Codex" and row["stage"] and row["next_action"]
                for row in self.console["integration_records"]
            )
        )
        self.assertTrue(
            all(
                row["role"]
                and "registered" not in row["role"].lower()
                and "adjudicated" not in row["role"].lower()
                for row in self.console["source_universe_records"]
            )
        )
        self.assertTrue(
            all(
                row["stage"]
                and "existing-manifestation" not in row["stage"]
                for row in self.console["media_records"]
            )
        )
        route_counts = {
            row["route"]: row["records"]
            for row in self.console["integration_routes"]
        }
        self.assertEqual(route_counts["FACT-001"], 44)
        self.assertEqual(route_counts["RIGHTS-002"], 23)

    def test_horizon_dashboard_uses_github_issue_and_project_snapshot(self) -> None:
        active = self.console["active_horizon_records"]
        closed = self.console["closed_horizon_records"]
        self.assertEqual(self.console["horizon_issue_count"], len(active))
        self.assertEqual(self.console["closed_horizon_issue_count"], len(closed))
        self.assertEqual(len(self.console["horizon_records"]), len(active) + len(closed))
        self.assertTrue(self.console["github_synced_at"])
        self.assertTrue(all(row["issue_state"] == "Open" for row in active))
        self.assertTrue(all(row["issue_state"] == "Closed" for row in closed))
        self.assertTrue(all(row["issue_url"].startswith("https://github.com/Thorncrag/ARRP/issues/") for row in active))
        self.assertFalse(any(row["status"] == "Project status unavailable" for row in active))
        for row in self.console["horizon_records"]:
            expected_sources = sum(row["id"] in item.get("routes", []) for item in self.console["source_queue_records"])
            expected_monitoring = sum(row["id"] in item.get("routes", []) for item in self.console["monitoring_records"])
            self.assertEqual(row["source_task_count"], expected_sources)
            self.assertEqual(row["monitoring_task_count"], expected_monitoring)

    def test_standalone_submission_prototype_has_minimal_lookup_and_page_context(self) -> None:
        expected = {
            row["Object ID"]
            for row in self.issue_registry
            if row["Kind"] == "proposal" and row["Object ID"]
        }
        proposal_index = self.participation["proposal_index"]
        self.assertEqual({row["id"] for row in proposal_index}, expected)
        self.assertTrue(all(row["area"] == row["id"].split("-", 1)[0] for row in proposal_index))
        self.assertTrue(all(row["title"] and row["issue_url"] for row in proposal_index))
        self.assertEqual(
            {row["id"] for row in self.participation["horizon_index"]},
            {row["id"] for row in self.console["active_horizon_records"]},
        )
        self.assertNotIn("proposal_index", self.console)

        participation_dir = ROOT / "participate"
        html = (participation_dir / "index.html").read_text(encoding="utf-8")
        app = (participation_dir / "app.js").read_text(encoding="utf-8")
        for field_id in {"submission-title", "submission-body", "submission-sources", "submission-related"}:
            self.assertIn(f'id="{field_id}"', html)
        self.assertIn('id="submission-context"', html)
        self.assertIn('id="submission-receipt"', html)
        self.assertIn('id="submission-discussion-link"', html)
        self.assertIn('id="submission-email"', html)
        self.assertIn('id="submission-email-consent"', html)
        self.assertIn('id="turnstile-container"', html)
        self.assertIn("watch the post for responses", html)
        self.assertIn("Subscribe", html)
        self.assertIn('params.get("page_title")', app)
        self.assertIn('params.get("page")', app)
        self.assertIn('params.get("proposal")', app)
        self.assertIn("ARRP_INTAKE_ENDPOINT", app)
        self.assertIn('intakeEndpoint("submit")', app)
        self.assertIn("full ARRP admission test", app)
        self.assertTrue((participation_dir / "vercel.json").exists())
        self.assertTrue((participation_dir / "api" / "submit.js").exists())
        self.assertTrue((participation_dir / ".env.example").exists())

        console_dir = RESEARCH / "horizon-review-console"
        console_html = (console_dir / "index.html").read_text(encoding="utf-8")
        console_app = (console_dir / "app.js").read_text(encoding="utf-8")
        self.assertIn("../../participate/index.html", console_html)
        self.assertIn("Proposed candidates", console_html)
        self.assertIn("Preliminary candidates", console_html)
        self.assertIn("This dashboard is read-only", console_html)
        self.assertNotIn('id="submission-view"', console_html)
        for control_id in {
            "decision-yes",
            "decision-no",
            "decision-defer",
            "decision-filter",
            "reviewer-notes",
            "review-file-actions",
        }:
            self.assertNotIn(f'id="{control_id}"', console_html)
        self.assertNotIn("screenSubmission", console_app)
        self.assertNotIn("setDecision", console_app)
        self.assertNotIn("localStorage", console_app)

    def test_qualitatively_placed_sources_are_on_issue_pages(self) -> None:
        placements = {
            "DOJ-002": ["docs.justia.com/cases/federal/district-courts/district-of-columbia"],
            "REG-001": ["fec.gov/documents/5867/usdcdc-mem-opinion-06-03-2025.pdf"],
            "RIGHTS-001": [
                "law.justia.com/cases/federal/district-courts/district-of-columbia/dcdce/1%3A2018cv01076",
                "supremecourt.gov/opinions/19pdf/19-431_5i36.pdf",
            ],
            "RIGHTS-002": ["law.justia.com/cases/federal/appellate-courts/ca9/18-16981"],
        }
        for issue_id, source_fragments in placements.items():
            area = issue_id.split("-", 1)[0]
            issue_path = ROOT / "areas" / area / "issues" / f"{issue_id}.md"
            evidence_path = ROOT / "areas" / area / "evidence" / f"{issue_id}-evidence.md"
            issue_text = issue_path.read_text(encoding="utf-8")
            for source_fragment in source_fragments:
                self.assertIn(source_fragment, issue_text)
            self.assertFalse(evidence_path.exists())

    def test_litigation_monitor_has_sources_and_defined_revisit_predicates(self) -> None:
        source_ids = {row["Source ID"] for row in self.sources}
        monitor_ids = [row["monitor_id"] for row in self.litigation_monitoring]
        self.assertEqual(len(monitor_ids), len(set(monitor_ids)))
        for row in self.litigation_monitoring:
            canonical_ids = {
                source_id.strip()
                for source_id in row["canonical_source_ids"].split(";")
                if source_id.strip()
            }
            self.assertTrue(canonical_ids)
            self.assertTrue(canonical_ids <= source_ids)
            self.assertTrue(row["revisit_trigger"].strip())

    def test_resolved_preliminary_candidates_leave_active_queue(self) -> None:
        self.assertEqual(self.candidates, [])
        self.assertFalse(any(row["candidate_id"] for row in self.routing))
        rendered_routes = {
            route.strip()
            for row in self.routing
            for route in row["integration_routes"].split(";")
            if route.strip()
        }
        source_routes = {
            route.strip()
            for row in self.sources
            for route in row["Associated Record IDs"].split(";")
            if route.strip()
        }
        self.assertFalse(any(route.startswith("INTAKE-GAP-") for route in rendered_routes | source_routes))
        for horizon_id in ("HOR-033", "HOR-034", "HOR-035", "HOR-036", "HOR-037"):
            self.assertIn(horizon_id, rendered_routes | source_routes)


if __name__ == "__main__":
    unittest.main()
