import csv
import json
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "research"


def read_csv(name: str) -> list[dict[str, str]]:
    with (RESEARCH / name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


class HorizonIntakeTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.catalog = read_csv("trump-administration-legal-review-catalog.csv")
        cls.routing = read_csv("trump-administration-evidence-routing.csv")
        cls.candidates = read_csv("trump-administration-preliminary-candidates.csv")
        with (ROOT / "inventory" / "sources.csv").open(newline="", encoding="utf-8") as handle:
            cls.sources = list(csv.DictReader(handle))
        bundle = (RESEARCH / "horizon-review-console" / "catalog-data.js").read_text(encoding="utf-8")
        prefix = "/* Generated by scripts/build_horizon_review_console.py. */\nwindow.ARRP_HORIZON_REVIEW_DATA="
        cls.console = json.loads(bundle.removeprefix(prefix).removesuffix(";\n"))

    def test_every_catalog_record_has_one_routing_record(self) -> None:
        catalog_ids = [row["catalog_id"] for row in self.catalog]
        routing_ids = [row["catalog_id"] for row in self.routing]
        self.assertGreater(len(catalog_ids), 0)
        self.assertEqual(len(catalog_ids), len(set(catalog_ids)))
        self.assertCountEqual(catalog_ids, routing_ids)

    def test_intake_level_review_has_no_pending_records(self) -> None:
        self.assertFalse(any(row["review_status"].endswith("pending") for row in self.routing))
        self.assertFalse(any(row["disposition"] == "agent-review-needed" for row in self.routing))

    def test_routes_use_current_record_identifiers(self) -> None:
        routes = {
            route.strip()
            for row in self.routing
            for route in row["integration_routes"].split(";")
            if route.strip()
        }
        self.assertFalse(any(route.startswith("A-") for route in routes))

    def test_console_contains_only_known_preliminary_candidates(self) -> None:
        candidate_ids = {row["candidate_id"] for row in self.candidates}
        active_candidate_ids = {
            row["candidate_id"]
            for row in self.candidates
            if row["review_status"] == "preliminary-candidate"
        }
        routed_candidate_ids = {row["candidate_id"] for row in self.routing if row["candidate_id"]}
        console_ids = {row["id"] for row in self.console["records"]}
        self.assertTrue(routed_candidate_ids <= candidate_ids)
        self.assertEqual(console_ids, active_candidate_ids)
        self.assertTrue(all(row["kind"] == "preliminary_candidate" for row in self.console["records"]))

    def test_resolved_preliminary_candidates_leave_active_queue(self) -> None:
        self.assertEqual(self.candidates, [])
        self.assertFalse(any(row["candidate_id"] for row in self.routing))
        rendered_routes = {
            route.strip()
            for row in self.routing
            for route in row["integration_routes"].split(";")
            if route.strip()
        }
        source_routes = {
            route.strip()
            for row in self.sources
            for route in row["Associated Record IDs"].split(";")
            if route.strip()
        }
        self.assertFalse(any(route.startswith("INTAKE-GAP-") for route in rendered_routes | source_routes))
        for horizon_id in ("HOR-033", "HOR-034", "HOR-035", "HOR-036", "HOR-037"):
            self.assertIn(horizon_id, rendered_routes | source_routes)


if __name__ == "__main__":
    unittest.main()
