/* Generated by scripts/build_horizon_review_console.py. */
window.ARRP_HORIZON_REVIEW_DATA={
  "schema_version": 27,
  "contract_schema_version": 1,
  "generation_id": "project-console-1d6aef983851e86dd50d",
  "source_revision": "d1820256edccd0c7a6f53f35788f2511ecde9578",
  "generated_at": "2026-07-26T02:52:44+00:00",
  "expected_count": 5639,
  "actual_count": 5639,
  "source_hashes": {
    ".github/case-monitor-bot.json": "sha256:15e31e00534a6cbb616ae4495ee01e1303e73877ff3fd17137f65a446978b15c",
    ".github/presidential-directives-bot.json": "sha256:c1e9d7826d9b34530b3c78be71594ce7d15c9144e2e471dfe5b87f68920c1027",
    ".github/source-checker-bot.json": "sha256:46f1a3767d4ada5e836c8ef9350dc4cf6b9fc0aac576d240623e1e976985c6a2",
    "feed:integrity": "sha256:bec66f2fa4cb24ef38200512df817aa383b6208be9419bc001ee2df9bee391a9",
    "feed:progress": "sha256:08a16a57072d100aa591f7999668ebc3ce682a30167ae9c60e75c5a3fa1abdca",
    "feed:run_chain": "sha256:a1736f6962aace4db26b65ea06536cea31a50f065aee4fe3cbb0fcd90d22e1af",
    "feed:source_checker": "sha256:f17cfe9222833bbbf416ff7e887a6e361b210e59be1e62b30af14d821eb99776",
    "framework/logs/AGENT_AUDIT_LOG.md": "sha256:ee68e053ac268c78abc046929e4c08055c7793294882a0844ee50ff808d689af",
    "framework/logs/CHANGE_AUDIT_LOG.md": "sha256:c097ef9bd6f65a62070a702d2a64b837d2a76a341a74f2c0c1efb2dea0c1a7c8",
    "framework/logs/ELIM_RUN_LOG.md": "sha256:bb7d8e1aaf3b5a1e7879268da7a20c23d4a0fb14955eb3a6be7dad5271503508",
    "framework/logs/HORIZON_SCAN_LOG.md": "sha256:3b286d6601cb81d7cd7f67d5a4cb56f19800f71997e8426529f64aa86beeac67",
    "framework/logs/SOURCE_MONITOR_LOG.md": "sha256:3fa377feffae734bad4fdc460346a71b2023faad446766425c8e94332b1c302f",
    "framework/print-assembly.json": "sha256:a893ac698b5ff4e3b00dafa87e072023fe504329bbef7db00acee63cdb0d529d",
    "inventory/github_issue_registry.csv": "sha256:3e85d2b624fa507dce13adba047a515c3f5c87e146957213bcf8848bf11d483c",
    "inventory/presidential-directives.csv": "sha256:01de9333614e09292d31055e3610985fa22bc0bf562cb645db1e3d073fbf2028",
    "inventory/sources-pending.csv": "sha256:c6eafc0d61b601ee1db9c12e9271797eba4c0abd3f7bf75021df916989f5433c",
    "inventory/sources.csv": "sha256:97f65cc569bc87ca53c9312e31f9702675b2a272c60a38b2c89e4b8a76015b5d",
    "research/README.md": "sha256:7ce219fc718f64c6f9757eaceefb4546b824fbd6deba37a4ddbcd0a63655301c",
    "research/trump-administration-preliminary-candidates.csv": "sha256:e31b51386bfc440d1ff6a5b9b333fe9b9f3071479f33ff4b62eb3488c69dc034"
  },
  "availability": "stale",
  "completeness": {
    "complete": false,
    "expected_count": 5639,
    "actual_count": 5639,
    "missing_count": 0
  },
  "pagination": {
    "complete": false,
    "sources": [
      {
        "source": "horizon-issues",
        "complete": true,
        "actual_count": 25,
        "mode": "authenticated-refresh"
      },
      {
        "source": "monitoring-issues",
        "complete": true,
        "actual_count": 32,
        "mode": "authenticated-refresh"
      },
      {
        "source": "progress",
        "complete": true,
        "details": {
          "complete": true,
          "sources": [
            {
              "actual_count": 110,
              "complete": true,
              "source": "github-project-items"
            },
            {
              "complete": true,
              "item_count": 110,
              "page_size": 100,
              "source": "github-project-field-values"
            },
            {
              "complete": true,
              "item_count": 110,
              "page_size": 100,
              "source": "github-project-sub-issues"
            },
            {
              "assignee_page_size": 20,
              "complete": true,
              "item_count": 110,
              "label_page_size": 100,
              "source": "github-project-labels-and-assignees"
            }
          ]
        }
      },
      {
        "source": "source-checker",
        "complete": false,
        "details": null
      }
    ]
  },
  "projection_errors": [
    {
      "code": "required_feed_contract_unavailable",
      "severity": "error",
      "feed": "source_checker",
      "message": "The source_checker feed is preserved as legacy data but lacks a generation truth contract."
    },
    {
      "code": "required_feed_not_current",
      "severity": "error",
      "feed": "source_checker",
      "availability": "stale",
      "message": "The source_checker feed is present but does not completely cover its current authoritative source."
    }
  ],
  "freshness": {
    "status": "stale",
    "basis": "source revision, completeness, and owning-process synchronization",
    "supersession_rule": "A newer authoritative source revision or generation supersedes this projection immediately, regardless of elapsed age."
  },
  "github_synced_at": "2026-07-26T02:52:37+00:00",
  "candidate_questions": 1,
  "horizon_issue_count": 17,
  "records": [
    {
      "id": "INTAKE-GAP-013",
      "title": "Executive Circumvention of Congressionally Assigned Smithsonian Governance",
      "summary": "A President may use executive-controlled property, appropriations administration, contracts, or other agency leverage to displace or circumvent governance authority that Congress assigned to a cross-branch public trust institution, without obtaining a statutory change or a decision through that institution's governing board.",
      "kind": "preliminary_candidate"
    }
  ],
  "active_horizon_records": [
    {
      "id": "HOR-010",
      "title": "Immigration-courthouse arrests and courthouse-access chilling",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/15",
      "workflow_status": "Deferred",
      "horizon_history": {
        "original_concern": "Immigration-courthouse arrests and the risk that enforcement activity deters participation in immigration or other judicial proceedings."
      }
    },
    {
      "id": "HOR-023",
      "title": "Foreign Election Interference and Campaign Counterintelligence Safeguards",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/234",
      "workflow_status": "Deferred",
      "horizon_history": {
        "original_concern": "Foreign election interference and campaign counterintelligence safeguards arising from the Mueller Report foreign-interference record and related Durham/FISA process source-development questions."
      }
    },
    {
      "id": "HOR-026",
      "title": "Presidential Withdrawal or Constructive Withdrawal from International Commitments",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/245",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Presidential formal or constructive withdrawal from congressionally or Senate-approved international organizations, alliances, treaty commitments, and comparable international institutions through withdrawal notices, participation suspension, deliberate arrears, representative vacancies, or circumvention of statutory safeguards."
      }
    },
    {
      "id": "HOR-027",
      "title": "Presidential Policymaking Through Privately Controlled Social Media",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/247",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "A President may use a personal or privately controlled social-media account as the initial or exclusive channel for major policy decisions, directives, foreign-policy positions, or other consequential official announcements."
      }
    },
    {
      "id": "HOR-029",
      "title": "Presidential Self-Dealing Through an Officially Favored Private Platform",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/249",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Presidential use of an officially favored communications platform in which the President retains a substantial beneficial financial interest may allow a president-beneficial company to monetize official conduct and information."
      }
    },
    {
      "id": "HOR-031",
      "title": "Durability and Revocation of National Monument Protections",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/251",
      "workflow_status": "Blocked",
      "horizon_history": {
        "original_concern": "An already-established national monument may lack durable protection if a successor President can unilaterally abolish it or materially diminish its protected boundary."
      }
    },
    {
      "id": "HOR-033",
      "title": "Enforceability of Accessibility Duties for Presidential Communications",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/253",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Existing accessibility duties for presidential and White House communications may lack a sufficiently explicit private enforcement route or sufficiently timely remedy."
      }
    },
    {
      "id": "HOR-035",
      "title": "Executive Review Evasion Through Withdrawal, Replacement, Settlement, or Mootness",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/255",
      "workflow_status": "Research",
      "horizon_history": {
        "original_concern": "Executive defendants may withdraw, replace, narrow, settle, or temporarily cease challenged conduct after harm occurs and thereby avoid a durable merits ruling without repairing the underlying authority or process weakness."
      }
    },
    {
      "id": "HOR-037",
      "title": "Immigration Detention, Removal Process, and Access Safeguards",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/257",
      "workflow_status": "Research",
      "horizon_history": {
        "original_concern": "Civil immigration detention, transfer, or removal may be completed or materially advanced before meaningful judicial review can occur, making a later legal victory incapable of fully repairing the harm."
      }
    },
    {
      "id": "HOR-038",
      "title": "Endangered Species Act Regulatory-Boundary Monitoring",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/274",
      "workflow_status": "Deferred",
      "horizon_history": {
        "original_concern": "Finalized 2026 regulations under ESA sections 4(d) and 4(b)(2) may reveal a statutory-boundary or timely-remedy weakness if delegated discretion displaces congressionally prescribed decision criteria or causes difficult-to-repair loss before review."
      }
    },
    {
      "id": "HOR-039",
      "title": "Functional Accessibility of Existing Lawful Immigration and Residency Pathways",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/300",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Lawful immigration and residency pathways created by Congress may become functionally inaccessible when statutory eligibility is not matched by adequate processing capacity, transparent queue administration, reasonable timelines, status-continuity protections, consistent standards, records access, or meaningful review."
      }
    },
    {
      "id": "HOR-040",
      "title": "Safeguards for Broad Presidential Tariff Delegations",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/302",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Economically consequential tariffs may be imposed, escalated, negotiated, or selectively waived under several broad trade-statute delegations without contemporaneous legislative approval or uniform safeguards."
      }
    },
    {
      "id": "HOR-041",
      "title": "Safeguards for Class-Based Presidential Entry Suspensions",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/303",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "INA section 212(f) may permit broad class-based entry suspensions through generalized detrimental-interest findings without a sufficiently specific statutory nexus, fixed duration, transparent record, or timely review."
      }
    },
    {
      "id": "HOR-042",
      "title": "Minimum Safeguards for Presidential Statutory Waivers",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/304",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Statutes may authorize a President to suspend enacted substantive or procedural safeguards through broad findings without consistent minimum requirements for reasons, scope, duration, notice, reporting, or review."
      }
    },
    {
      "id": "HOR-043",
      "title": "Presidential Recognition of International Bodies With Domestic Legal Privileges",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/305",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Existing law may permit a President to recognize an international body, determine U.S. participation, and confer federal privileges, exemptions, and immunities without a distinct congressional participation decision or clear accountability safeguards."
      }
    },
    {
      "id": "HOR-044",
      "title": "Statutory Framework for Presidential Cross-Border Infrastructure Permits",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/306",
      "workflow_status": "Development",
      "horizon_history": {
        "original_concern": "Cross-border pipelines, railways, bridges, and comparable facilities may be approved through a presidential permitting system created substantially by executive practice without uniform statutory criteria or procedures, and some decisions may fall outside ordinary APA review."
      }
    },
    {
      "id": "HOR-045",
      "title": "Immigration-Enforcement Vehicle-Stop Safeguards",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/311",
      "workflow_status": "Deferred",
      "horizon_history": {
        "original_concern": "Immigration-enforcement vehicle stops may lack sufficiently durable and measurable safeguards for particularized suspicion, target verification, documentation, signaling, de-escalation, and public reporting."
      }
    }
  ],
  "monitoring_issues": [
    {
      "id": "HOR-033",
      "title": "Enforceability of Accessibility Duties for Presidential Communications",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/253"
    },
    {
      "id": "HOR-037",
      "title": "Immigration Detention, Removal Process, and Access Safeguards",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/257"
    },
    {
      "id": "CIV-001",
      "title": "Civil-Service Merit, Classification, and Anti-Politicization",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/86"
    },
    {
      "id": "CIV-009",
      "title": "Repurposed technical units as cross-agency operational control mechanisms",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/94"
    },
    {
      "id": "CIV-010",
      "title": "Congressional Authorization for Secondary Use of Government-Held Personal Data",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/254"
    },
    {
      "id": "DOJ-002",
      "title": "White House Direction or Interference in Particular Federal Criminal Matters",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/23"
    },
    {
      "id": "DOJ-003",
      "title": "Politically Selective Enforcement, Charging, and Favoritism",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/24"
    },
    {
      "id": "DOM-001",
      "title": "Domestic Deployment Authorities and Safeguards",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/135"
    },
    {
      "id": "DOM-005",
      "title": "State Investigative Access to Federal Critical-Incident Evidence",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/139"
    },
    {
      "id": "ELEC-001",
      "title": "Federal Executive Interference with State and Local Election Administration",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/29"
    },
    {
      "id": "ELEC-004",
      "title": "Abuse of Election Litigation and Civil Process",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/32"
    },
    {
      "id": "ELEC-013",
      "title": "Federal Candidate Access, Ballot Access, and Debate Gatekeeping",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/41"
    },
    {
      "id": "EMERG-003",
      "title": "Emergency Economic Powers as a Substitute for Legislation",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/105"
    },
    {
      "id": "EMOL-001",
      "title": "Presidential Financial Conflicts, Emoluments, and Self-Dealing",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/59"
    },
    {
      "id": "FACT-001",
      "title": "Scientific, Statistical, and Technical Integrity",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/168"
    },
    {
      "id": "FED-002",
      "title": "Selective or Retaliatory Federal Administration Against States",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/186"
    },
    {
      "id": "FED-003",
      "title": "Federal Funding, Waiver, and Approval Coercion of States",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/187"
    },
    {
      "id": "FED-004",
      "title": "Federal Displacement of State Functions",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/188"
    },
    {
      "id": "FUND-001",
      "title": "Fiscal Implementation of Ultra Vires Executive Directives",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/111"
    },
    {
      "id": "HER-001",
      "title": "Federal Civic Property Preservation and Public Review",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/213"
    },
    {
      "id": "JUD-001",
      "title": "Executive Dependence of Judicial Enforcement",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/43"
    },
    {
      "id": "OVS-001",
      "title": "Inspector General Independence, Access, Reporting, and Follow-Through",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/95"
    },
    {
      "id": "PRESS-001",
      "title": "Equal Press Access and Rapid Review",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/201"
    },
    {
      "id": "REC-001",
      "title": "Presidential and Executive Records Integrity, Custody, and Enforcement",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/127"
    },
    {
      "id": "REG-001",
      "title": "Agency Independence and Functional Nullification",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/160"
    },
    {
      "id": "REG-002",
      "title": "Executive Influence over Federal Regulatory Enforcement",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/161"
    },
    {
      "id": "REG-003",
      "title": "Control of Administrative Adjudication",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/162"
    },
    {
      "id": "RET-001",
      "title": "Executive Retaliation Through Federal Benefits and Regulatory Power",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/177"
    },
    {
      "id": "RIGHTS-001",
      "title": "Civil-Rights Administration, Identity Records, and Federal Definition Control",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/221"
    },
    {
      "id": "RIGHTS-002",
      "title": "Temporary Protected Status, Asylum Access, and Humanitarian Reviewability",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/222"
    },
    {
      "id": "WAR-001",
      "title": "Comprehensive War Powers and Use-of-Force Authorization Reform",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/42"
    },
    {
      "id": "WAR-009",
      "title": "Executive Lethal Targeting and Accountability",
      "issue_url": "https://github.com/Thorncrag/ARRP/issues/347"
    }
  ],
  "repository_review_recommendations": [
    {
      "id": "SMR-20260725-PR380",
      "recorded_at": "2026-07-25T22:17:39Z",
      "reviewer": "Interactive Codex",
      "pull_request_number": 380,
      "pull_request_url": "https://github.com/Thorncrag/ARRP/pull/380",
      "head_revision": "ba3dc636710633c25c1f4776cc67059e96d02478",
      "proposal_event_id": "SDE-93345EDC1D1AC55F8CFA3E44",
      "recommendation": "Close without merge; after the complete-delta correction reaches main, rerun Case Monitor from current main and review the regenerated, fully itemized proposal. Separately route the July 23 Suri appellate decision to RIGHTS-002 and assess it as a possible control example for HOR-035.",
      "rationale": "The pull-request narrative reports one changed source, SRC-2238, while the exact pending head changes 42 source records plus the HOR-035 generated lead set. The July 23 Suri opinion preserves habeas jurisdiction and identifies disagreement among circuits; the watcher's settlement-token match does not describe that holding. The present narrative therefore cannot support informed acceptance of the complete branch.",
      "affected_records": "43 records in the bound event: HOR-035 and 42 source records, including SRC-2238.",
      "confidence": "High confidence that the pull-request narrative materially underreports its exact-head delta and that Suri requires substantive review; the final project characterization and any source integration remain subject to ordinary issue-development review.",
      "action_owner": "Human",
      "human_question": "Approve closing PR #380 without merge so the corrected watcher can regenerate a complete proposal from current main?",
      "reassessment_trigger": "Any change to the pull-request head invalidates this recommendation and returns the complete proposal to Elim review.",
      "heading": "2026-07-25T22:17:39Z — Repository review recommendation SMR-20260725-PR380",
      "affected": {
        "complete": true,
        "total_count": 43,
        "records": [
          {
            "record_id": "HOR-035",
            "record_type": "candidate"
          },
          {
            "record_id": "SRC-0632",
            "record_type": "source"
          },
          {
            "record_id": "SRC-0945",
            "record_type": "source"
          },
          {
            "record_id": "SRC-0965",
            "record_type": "source"
          },
          {
            "record_id": "SRC-0982",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1004",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1052",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1056",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1093",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1929",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1930",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1932",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1933",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1934",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1940",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1941",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1942",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1943",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1946",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1952",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1957",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1973",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1979",
            "record_type": "source"
          },
          {
            "record_id": "SRC-1982",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2042",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2080",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2081",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2105",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2110",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2136",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2149",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2190",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2216",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2221",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2235",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2238",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2351",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2591",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2649",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2651",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2652",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2653",
            "record_type": "source"
          },
          {
            "record_id": "SRC-2654",
            "record_type": "source"
          }
        ],
        "record_ids": [
          "HOR-035",
          "SRC-0632",
          "SRC-0945",
          "SRC-0965",
          "SRC-0982",
          "SRC-1004",
          "SRC-1052",
          "SRC-1056",
          "SRC-1093",
          "SRC-1929",
          "SRC-1930",
          "SRC-1932",
          "SRC-1933",
          "SRC-1934",
          "SRC-1940",
          "SRC-1941",
          "SRC-1942",
          "SRC-1943",
          "SRC-1946",
          "SRC-1952",
          "SRC-1957",
          "SRC-1973",
          "SRC-1979",
          "SRC-1982",
          "SRC-2042",
          "SRC-2080",
          "SRC-2081",
          "SRC-2105",
          "SRC-2110",
          "SRC-2136",
          "SRC-2149",
          "SRC-2190",
          "SRC-2216",
          "SRC-2221",
          "SRC-2235",
          "SRC-2238",
          "SRC-2351",
          "SRC-2591",
          "SRC-2649",
          "SRC-2651",
          "SRC-2652",
          "SRC-2653",
          "SRC-2654"
        ],
        "by_type": {
          "candidate": [
            "HOR-035"
          ],
          "source": [
            "SRC-0632",
            "SRC-0945",
            "SRC-0965",
            "SRC-0982",
            "SRC-1004",
            "SRC-1052",
            "SRC-1056",
            "SRC-1093",
            "SRC-1929",
            "SRC-1930",
            "SRC-1932",
            "SRC-1933",
            "SRC-1934",
            "SRC-1940",
            "SRC-1941",
            "SRC-1942",
            "SRC-1943",
            "SRC-1946",
            "SRC-1952",
            "SRC-1957",
            "SRC-1973",
            "SRC-1979",
            "SRC-1982",
            "SRC-2042",
            "SRC-2080",
            "SRC-2081",
            "SRC-2105",
            "SRC-2110",
            "SRC-2136",
            "SRC-2149",
            "SRC-2190",
            "SRC-2216",
            "SRC-2221",
            "SRC-2235",
            "SRC-2238",
            "SRC-2351",
            "SRC-2591",
            "SRC-2649",
            "SRC-2651",
            "SRC-2652",
            "SRC-2653",
            "SRC-2654"
          ]
        },
        "source_ids": [
          "SRC-0632",
          "SRC-0945",
          "SRC-0965",
          "SRC-0982",
          "SRC-1004",
          "SRC-1052",
          "SRC-1056",
          "SRC-1093",
          "SRC-1929",
          "SRC-1930",
          "SRC-1932",
          "SRC-1933",
          "SRC-1934",
          "SRC-1940",
          "SRC-1941",
          "SRC-1942",
          "SRC-1943",
          "SRC-1946",
          "SRC-1952",
          "SRC-1957",
          "SRC-1973",
          "SRC-1979",
          "SRC-1982",
          "SRC-2042",
          "SRC-2080",
          "SRC-2081",
          "SRC-2105",
          "SRC-2110",
          "SRC-2136",
          "SRC-2149",
          "SRC-2190",
          "SRC-2216",
          "SRC-2221",
          "SRC-2235",
          "SRC-2238",
          "SRC-2351",
          "SRC-2591",
          "SRC-2649",
          "SRC-2651",
          "SRC-2652",
          "SRC-2653",
          "SRC-2654"
        ],
        "directive_ids": [],
        "issue_development_ids": [
          "HOR-035"
        ],
        "issue_development_count": 1
      },
      "event_source_url": "https://github.com/Thorncrag/ARRP/blob/project-console-data/source-domain-events/proposed/case-monitor-bot/SDE-93345EDC1D1AC55F8CFA3E44.json",
      "source_url": "https://github.com/Thorncrag/ARRP/blob/main/framework/logs/SOURCE_MONITOR_LOG.md",
      "console_target": "logs:source-monitor"
    },
    {
      "id": "SMR-20260725-PR381",
      "recorded_at": "2026-07-25T22:17:40Z",
      "reviewer": "Interactive Codex",
      "pull_request_number": 381,
      "pull_request_url": "https://github.com/Thorncrag/ARRP/pull/381",
      "head_revision": "71525e1d2bc27c31a5c1b455243259b1b541adff",
      "proposal_event_id": "SDE-578F200E8E9344ADF613CA76",
      "recommendation": "Close without merge; after the complete-delta correction reaches main, rerun the Presidential Directives Bot and screen the regenerated full proposal. Route the four trade proclamations to HOR-040 source development, route Executive Order 14415 to FACT-009 source development, and record no separate project action for the two ceremonial proclamations, the Mali continuation, or the two relationship-only metadata updates unless later evidence changes that assessment.",
      "rationale": "The pull-request narrative says New: 0 and Changed: 2, while the exact pending head contains eight new directives and two changed relationship fields. Four new proclamations invoke tariff authorities already owned by HOR-040, and Executive Order 14415 repeatedly uses the disputed Department of War terminology already owned by FACT-009. The other records are ceremonial or continuation metadata on the presently reviewed evidence. The current narrative omits most of the actual acceptance boundary.",
      "affected_records": "10 directives in the bound event: 2019-05370, 2019-16383, 2026-14990, 2026-14991, 2026-14992, 2026-14997, 2026-14998, 2026-14999, 2026-15003, and 2026-15024.",
      "confidence": "High confidence in the incomplete-delta diagnosis and the existing HOR-040 and FACT-009 routes; ordinary source-development review must still determine what propositions, if any, warrant integration.",
      "action_owner": "Human",
      "human_question": "Approve closing PR #381 without merge so the corrected watcher can regenerate and itemize all ten pending directives from current main?",
      "reassessment_trigger": "Any change to the pull-request head invalidates this recommendation and returns the complete proposal to Elim review.",
      "heading": "2026-07-25T22:17:40Z — Repository review recommendation SMR-20260725-PR381",
      "affected": {
        "complete": true,
        "total_count": 10,
        "records": [
          {
            "record_id": "2019-05370",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2019-16383",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-14990",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-14991",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-14992",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-14997",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-14998",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-14999",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-15003",
            "record_type": "presidential-directive"
          },
          {
            "record_id": "2026-15024",
            "record_type": "presidential-directive"
          }
        ],
        "record_ids": [
          "2019-05370",
          "2019-16383",
          "2026-14990",
          "2026-14991",
          "2026-14992",
          "2026-14997",
          "2026-14998",
          "2026-14999",
          "2026-15003",
          "2026-15024"
        ],
        "by_type": {
          "presidential-directive": [
            "2019-05370",
            "2019-16383",
            "2026-14990",
            "2026-14991",
            "2026-14992",
            "2026-14997",
            "2026-14998",
            "2026-14999",
            "2026-15003",
            "2026-15024"
          ]
        },
        "source_ids": [],
        "directive_ids": [
          "2019-05370",
          "2019-16383",
          "2026-14990",
          "2026-14991",
          "2026-14992",
          "2026-14997",
          "2026-14998",
          "2026-14999",
          "2026-15003",
          "2026-15024"
        ],
        "issue_development_ids": [],
        "issue_development_count": 0
      },
      "event_source_url": "https://github.com/Thorncrag/ARRP/blob/project-console-data/source-domain-events/proposed/presidential-directives-bot/SDE-578F200E8E9344ADF613CA76.json",
      "source_url": "https://github.com/Thorncrag/ARRP/blob/main/framework/logs/SOURCE_MONITOR_LOG.md",
      "console_target": "logs:source-monitor"
    }
  ],
  "overview": {
    "manager_focus": {
      "human_decisions": 3,
      "human_actions": [
        {
          "id": "SMR-20260725-PR380",
          "kind": "repository_review_decision",
          "label": "Approve closing PR #380 without merge so the corrected watcher can regenerate a complete proposal from current main?",
          "priority": "Human decision",
          "route": "logs:source-monitor",
          "source_url": "https://github.com/Thorncrag/ARRP/blob/main/framework/logs/SOURCE_MONITOR_LOG.md"
        },
        {
          "id": "SMR-20260725-PR381",
          "kind": "repository_review_decision",
          "label": "Approve closing PR #381 without merge so the corrected watcher can regenerate and itemize all ten pending directives from current main?",
          "priority": "Human decision",
          "route": "logs:source-monitor",
          "source_url": "https://github.com/Thorncrag/ARRP/blob/main/framework/logs/SOURCE_MONITOR_LOG.md"
        },
        {
          "id": "JUD-009",
          "kind": "project_human_decision",
          "label": "JUD-009: Supreme Court Ethics, Recusal, and Transparency",
          "priority": "High",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/47"
        }
      ],
      "active_incidents": 2,
      "incidents": [
        {
          "incident_id": "incident-33588a859e02e349",
          "stage": "host-repository-preflight",
          "failed_prerequisite": "host-repository-preflight",
          "root_cause": "Canonical ARRP workspace is off main and not reconciled with GitHub.",
          "classification": "hold",
          "message": "Canonical ARRP workspace is off main and not reconciled with GitHub.",
          "occurrence_count": 32,
          "first_seen": "2026-07-25T20:08:54+00:00",
          "latest_seen": "2026-07-26T02:49:40+00:00",
          "chain_ids": [
            "host-dispatch-20260726T024940Z",
            "host-dispatch-20260725T200854Z",
            "host-dispatch-20260725T210904Z",
            "host-dispatch-20260725T211905Z",
            "host-dispatch-20260725T212906Z",
            "host-dispatch-20260725T213907Z",
            "host-dispatch-20260725T221915Z",
            "host-dispatch-20260725T222916Z",
            "host-dispatch-20260725T223916Z",
            "host-dispatch-20260725T225922Z",
            "host-dispatch-20260725T230923Z",
            "host-dispatch-20260725T231923Z",
            "host-dispatch-20260725T232924Z",
            "host-dispatch-20260725T233925Z",
            "host-dispatch-20260725T234926Z",
            "host-dispatch-20260725T235926Z",
            "host-dispatch-20260726T000927Z",
            "host-dispatch-20260726T001928Z",
            "host-dispatch-20260726T002929Z",
            "host-dispatch-20260726T003929Z",
            "host-dispatch-20260726T004930Z",
            "host-dispatch-20260726T005931Z",
            "host-dispatch-20260726T010932Z",
            "host-dispatch-20260726T011932Z",
            "host-dispatch-20260726T012933Z",
            "host-dispatch-20260726T013935Z",
            "host-dispatch-20260726T014936Z",
            "host-dispatch-20260726T015936Z",
            "host-dispatch-20260726T020937Z",
            "host-dispatch-20260726T021938Z",
            "host-dispatch-20260726T022939Z",
            "host-dispatch-20260726T023939Z"
          ],
          "route": "automation"
        },
        {
          "incident_id": "incident-91c7ce76fe32a431",
          "stage": "elim-isolated-checkout",
          "failed_prerequisite": "elim-isolated-checkout",
          "root_cause": "The isolated Elim checkout contains a prior unsynchronized baseline.",
          "classification": "blocking",
          "message": "The isolated Elim checkout contains a prior unsynchronized baseline.",
          "occurrence_count": 5,
          "first_seen": "2026-07-25T11:17:54+00:00",
          "latest_seen": "2026-07-25T22:49:21+00:00",
          "chain_ids": [
            "arrp-20260725T110820Z",
            "arrp-20260725T114639Z",
            "arrp-20260725T201420Z",
            "arrp-20260725T214010Z",
            "arrp-20260725T224436Z"
          ],
          "route": "automation"
        }
      ],
      "release_blockers": 26,
      "release_blocker_fields_available": true,
      "critical_high_release_blockers": 24,
      "critical_high_blocker_items": [
        {
          "identifier": "DOJ-001",
          "title": "DOJ-001: Recent Presidential Personal Counsel in Senior DOJ Leadership",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/22",
          "route": "progress"
        },
        {
          "identifier": "DOJ-002",
          "title": "DOJ-002: White House Direction or Interference in Particular Federal Criminal Matters",
          "priority": "High",
          "status": "Research",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/23",
          "route": "progress"
        },
        {
          "identifier": "DOJ-003",
          "title": "DOJ-003: Politically Selective Enforcement, Charging, and Favoritism",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/24",
          "route": "progress"
        },
        {
          "identifier": "DOJ-005",
          "title": "DOJ-005: Weak Enforcement and Internal Control of DOJ Recusal Duties",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/26",
          "route": "progress"
        },
        {
          "identifier": "DOJ-007",
          "title": "DOJ-007: Independent Investigation of Presidential and Senior Executive Misconduct",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/27",
          "route": "progress"
        },
        {
          "identifier": "DOJ-009",
          "title": "DOJ-009: Insufficient Professional-Qualification Requirements for Senior DOJ Leadership",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/28",
          "route": "progress"
        },
        {
          "identifier": "ELEC-001",
          "title": "ELEC-001: Federal Executive Interference with State and Local Election Administration",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/29",
          "route": "progress"
        },
        {
          "identifier": "ELEC-002",
          "title": "ELEC-002: Pressure on Certification and Canvassing Officials",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/30",
          "route": "progress"
        },
        {
          "identifier": "ELEC-003",
          "title": "ELEC-003: Insufficient Protection for Election Workers and Officials",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/31",
          "route": "progress"
        },
        {
          "identifier": "ELEC-004",
          "title": "ELEC-004: Abuse of Election Litigation and Civil Process",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/32",
          "route": "progress"
        },
        {
          "identifier": "ELEC-005",
          "title": "ELEC-005: Weak Safeguards Against False Presidential Result-Transmission Documents",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/33",
          "route": "progress"
        },
        {
          "identifier": "ELEC-006",
          "title": "ELEC-006: Insufficiently Automatic Presidential-Transition Procedures",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/34",
          "route": "progress"
        },
        {
          "identifier": "ELEC-007",
          "title": "ELEC-007: Improper Federal-Force Presence in Election Administration",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/35",
          "route": "progress"
        },
        {
          "identifier": "ELEC-008",
          "title": "ELEC-008: Accountability for Coordinated Federal Election-Subversion Schemes",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/36",
          "route": "progress"
        },
        {
          "identifier": "ELEC-009",
          "title": "ELEC-009: Electoral College Structure and National Popular Vote",
          "priority": "High",
          "status": "External review",
          "workstream": "Proposal development",
          "url": "https://github.com/Thorncrag/ARRP/issues/37",
          "route": "progress"
        }
      ],
      "integrity_findings": 0,
      "integrity_findings_available": true,
      "source_checker_complete": false,
      "delivery_items": 12,
      "delivery_items_available": true,
      "domain_attention": [
        {
          "domain": "source_checker",
          "status": "stale",
          "reason": "The feed does not completely cover its current authoritative source.",
          "timestamp": "2026-07-24T14:14:17Z",
          "route": "sources:assurance"
        },
        {
          "domain": "automation",
          "status": "attention",
          "reason": "The current run chain reports an active failure or hold.",
          "timestamp": "2026-07-26T02:49:40+00:00",
          "route": "automation"
        },
        {
          "domain": "publication_release",
          "status": "not_determined",
          "reason": "Structural assembly facts are available, but release readiness cannot be declared without lineage-backed export validation, completed prerequisites, and a recorded human go/no-go decision.",
          "timestamp": null,
          "route": "publication:analysis"
        }
      ],
      "next_reviews": [
        {
          "kind": "review_epoch",
          "label": "Comprehensive Review Epoch",
          "due_at": "2026-08-07T15:40:02+00:00",
          "status": "evolving",
          "trigger": "The first biweekly comprehensive Review Epoch was due after material Run Coordinator and Elim host-boundary repairs.",
          "route": "logs:agents"
        },
        {
          "kind": "project_review_trigger",
          "label": "APPT-004",
          "due_at": null,
          "status": "Development",
          "trigger": "Source and boundary review of advice, representation, appointment status, supervision, ethics, records, security, and foreign-affairs limits",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/122"
        },
        {
          "kind": "project_review_trigger",
          "label": "CIV-001",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/86"
        },
        {
          "kind": "project_review_trigger",
          "label": "CIV-004",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/89"
        },
        {
          "kind": "project_review_trigger",
          "label": "CIV-005",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/90"
        },
        {
          "kind": "project_review_trigger",
          "label": "CIV-009",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/94"
        },
        {
          "kind": "project_review_trigger",
          "label": "CLASS-001",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/74"
        },
        {
          "kind": "project_review_trigger",
          "label": "CLASS-004",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/77"
        },
        {
          "kind": "project_review_trigger",
          "label": "CLASS-006",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/79"
        },
        {
          "kind": "project_review_trigger",
          "label": "CLASS-011",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/84"
        },
        {
          "kind": "project_review_trigger",
          "label": "CONG-001",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/144"
        },
        {
          "kind": "project_review_trigger",
          "label": "CONG-007",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/150"
        },
        {
          "kind": "project_review_trigger",
          "label": "DOJ-004",
          "due_at": null,
          "status": "Blocked",
          "trigger": "When a merits ruling or other controlling authority resolves the Article II predicate, reassess the available statutory remedy",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/25"
        },
        {
          "kind": "project_review_trigger",
          "label": "DOM-001",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/135"
        },
        {
          "kind": "project_review_trigger",
          "label": "DOM-007",
          "due_at": null,
          "status": "Development",
          "trigger": "Source development and initial vehicle drafting",
          "route": "progress",
          "source_url": "https://github.com/Thorncrag/ARRP/issues/141"
        }
      ]
    },
    "queue_counts": {
      "preliminary_candidates": 1,
      "formal_candidates": 17,
      "monitoring_issues": 32,
      "pending_sources": 0,
      "repository_recommendations": 2,
      "delivery_items": 12,
      "human_actions": 3,
      "active_incidents": 2,
      "critical_high_release_blockers": 24
    },
    "activity": [
      {
        "id": "agent-090",
        "log": "agents",
        "date": "2026-07-25T22:28:35Z",
        "record": "Dedicated Action Items repository-review listing, Elim exact-head recommendation protocol, and complete persistent-watcher proposal handoff",
        "title": "interactive Codex · Dedicated Action Items repository-review listing, Elim exact-head recommendation protocol, and complete persistent-watcher proposal handoff",
        "actor": "interactive Codex",
        "source": "Agent Audit Log",
        "outcome": "Completed",
        "affected_scope": "Dedicated Action Items repository-review listing, Elim exact-head recommendation protocol, and complete persistent-watcher proposal handoff",
        "summary": "interface governance and automation integrity",
        "manager_effect": null,
        "owner": "interactive Codex",
        "kind": "project_log",
        "route": "logs:agents",
        "collapsed_count": 1
      },
      {
        "id": "SMR-20260725-PR381",
        "date": "2026-07-25T22:17:40Z",
        "kind": "repository_review_recommendation",
        "title": "Interactive Codex · PR #381",
        "actor": "Interactive Codex",
        "source": "Source Monitor Log",
        "outcome": "Recommendation recorded",
        "affected_scope": "10 directives in the bound event: 2019-05370, 2019-16383, 2026-14990, 2026-14991, 2026-14992, 2026-14997, 2026-14998, 2026-14999, 2026-15003, and 2026-15024.",
        "summary": "Close without merge; after the complete-delta correction reaches main, rerun the Presidential Directives Bot and screen the regenerated full proposal. Route the four trade proclamations to HOR-040 source development, route Executive Order 14415 to FACT-009 source development, and record no separate project action for the two ceremonial proclamations, the Mali continuation, or the two relationship-only metadata updates unless later evidence changes that assessment.",
        "manager_effect": "Approve closing PR #381 without merge so the corrected watcher can regenerate and itemize all ten pending directives from current main?",
        "owner": "Human",
        "affected_count": 10,
        "route": "logs:source-monitor",
        "tone": "warning",
        "collapsed_count": 1
      },
      {
        "id": "SMR-20260725-PR380",
        "date": "2026-07-25T22:17:39Z",
        "kind": "repository_review_recommendation",
        "title": "Interactive Codex · PR #380",
        "actor": "Interactive Codex",
        "source": "Source Monitor Log",
        "outcome": "Recommendation recorded",
        "affected_scope": "43 records in the bound event: HOR-035 and 42 source records, including SRC-2238.",
        "summary": "Close without merge; after the complete-delta correction reaches main, rerun Case Monitor from current main and review the regenerated, fully itemized proposal. Separately route the July 23 Suri appellate decision to RIGHTS-002 and assess it as a possible control example for HOR-035.",
        "manager_effect": "Approve closing PR #380 without merge so the corrected watcher can regenerate a complete proposal from current main?",
        "owner": "Human",
        "affected_count": 43,
        "route": "logs:source-monitor",
        "tone": "warning",
        "collapsed_count": 1
      },
      {
        "id": "elim-run-010",
        "log": "elim",
        "date": "2026-07-25 04:07:39 -0400",
        "record": null,
        "title": "Elim Run Log · Failed before substantive work — false usage-window change and unavailable Git closeout",
        "actor": "Elim Run Log",
        "source": "Elim Run Log",
        "outcome": "Failed before substantive work — false usage-window change and unavailable Git closeout",
        "affected_scope": null,
        "summary": "Performed read-only launch preflight only. Verified the exact manifest-selected comprehensive unit, clean synchronized baseline, workflow health, deterministic stage statuses, every locally preserved input hash and byte count, the pinned queue and comprehensive packet hashes, clean Integrity result, empty public intake, and the due governing-boundary review trigger. The comprehensive review, project-wide sampling, finding adjudication, Review Epoch record, and scripts/record_review_epoch.py did not begin.",
        "manager_effect": null,
        "owner": null,
        "kind": "project_log",
        "route": "logs:elim",
        "collapsed_count": 1
      },
      {
        "id": "agent-087",
        "log": "agents",
        "date": "2026-07-24T14:58:03-04:00",
        "record": "GitHub Pages deployment-status grace repair",
        "title": "elim · GitHub Pages deployment-status grace repair",
        "actor": "elim",
        "source": "Agent Audit Log",
        "outcome": "Completed",
        "affected_scope": "GitHub Pages deployment-status grace repair",
        "summary": "integrity",
        "manager_effect": null,
        "owner": "elim",
        "kind": "project_log",
        "route": "logs:agents",
        "collapsed_count": 1
      },
      {
        "id": "elim-run-009",
        "log": "elim",
        "date": "2026-07-24 17:17:08 -0400",
        "record": null,
        "title": "Elim Run Log · Failed — Codex process terminated before verified closeout",
        "actor": "Elim Run Log",
        "source": "Elim Run Log",
        "outcome": "Failed — Codex process terminated before verified closeout",
        "affected_scope": null,
        "summary": "Verified the selected EMERG-003 issue-audit packet and performed read-only legal, source, drafting, and lifecycle review. The preserved event stream contains a proposed structured human_review result, but the Codex process ended with signal 15 before the dispatcher validated, applied, or canonically logged it. No T1 audit, score, **Runs** change, source change, lifecycle change, Project update, or human decision was completed or routed from this failed invocation.",
        "manager_effect": null,
        "owner": null,
        "kind": "project_log",
        "route": "logs:elim",
        "collapsed_count": 1
      },
      {
        "id": "agent-089",
        "log": "agents",
        "date": "2026-07-24 16:49:37 -0400",
        "record": "JUD-009",
        "title": "2 consecutive clean / no-op activities",
        "actor": "elim",
        "source": "Agent Audit Log",
        "outcome": "Completed",
        "affected_scope": "2 retained log activities",
        "summary": "Consecutive identical routine outcomes are collapsed here; the owning log retains every entry.",
        "manager_effect": "No manager action is recorded; open the owning log for complete retained history.",
        "owner": "elim",
        "kind": "collapsed_activity",
        "route": "logs:agents",
        "collapsed_count": 2
      },
      {
        "id": "elim-run-008",
        "log": "elim",
        "date": "2026-07-24 16:20:10 -0400",
        "record": null,
        "title": "Elim Run Log · Completed; one human-only decision routed",
        "actor": "Elim Run Log",
        "source": "Elim Run Log",
        "outcome": "Completed; one human-only decision routed",
        "affected_scope": null,
        "summary": "Verified the complete deterministic chain and every preserved input, then completed JUD-009's targeted Change Audit and Internal Remedy-Fit Audit. Revalidated current law, direct bills, constitutional uncertainty, the Supreme Court's 2026 conflict-checking improvement, remedy fit, drafting, implementation, abuse resistance, budget, and adoption. Recalculated the consolidated proposal at 77/100, preserved four T-audit Runs, cleared the Change Audit marker, and made bounded complaint, recusal-review, appointer-President, confidentiality, response, deadline, source, and legislative-form corrections. The new Framework requires the material application-under-different-control judgment from the human author, so the synchronized workflow is Human decision needed.",
        "manager_effect": null,
        "owner": null,
        "kind": "project_log",
        "route": "logs:elim",
        "collapsed_count": 1
      },
      {
        "id": "elim-run-007",
        "log": "elim",
        "date": "2026-07-24 14:55:29 -0400",
        "record": null,
        "title": "Elim Run Log · Completed",
        "actor": "Elim Run Log",
        "source": "Elim Run Log",
        "outcome": "Completed",
        "affected_scope": null,
        "summary": "Verified the complete deterministic chain, every preserved input, the pinned queue and integrity-reconciliation context, repository freshness, bot health, intake state, and Review Epoch state. Processed the highest-priority integrity unit. The pinned Integrity result captured the exact current GitHub Pages deployment while its newest status was in_progress; live readback showed that deployment and its public-site workflow had completed successfully. Repaired the detector so only nonterminal deployment states inside the existing 30-minute publication window receive grace; terminal failures and nonterminal states beyond that window remain errors.",
        "manager_effect": null,
        "owner": null,
        "kind": "project_log",
        "route": "logs:elim",
        "collapsed_count": 1
      }
    ],
    "agents": {
      "registered": 7,
      "last_chain_id": "host-dispatch-20260726T024940Z",
      "chain_status": "failed"
    },
    "services": {
      "case_monitor": {
        "enabled": true,
        "mode": "Scheduled; manual dispatch available",
        "bot_name": "case-monitor-bot",
        "provider": "just-security-litigation-tracker + courtlistener-rest-v4",
        "workflow_url": "https://github.com/Thorncrag/ARRP/actions/workflows/case-monitor-bot.yml"
      },
      "presidential_directives": {
        "enabled": true,
        "mode": "Scheduled; manual dispatch available",
        "bot_name": "presidential-directives-bot",
        "provider": "federal-register-api-v1",
        "workflow_url": "https://github.com/Thorncrag/ARRP/actions/workflows/presidential-directives-bot.yml"
      }
    },
    "usage": null,
    "progress_summary": {
      "generated_at": "2026-07-26T02:51:36+00:00",
      "source_revision": "d1820256edccd0c7a6f53f35788f2511ecde9578",
      "availability": "current",
      "ready": 27,
      "total": 81,
      "remaining": 54,
      "track_status": "On track",
      "delivery_items": 12
    },
    "integrity_summary": {
      "generated_at": "2026-07-26T02:52:14+00:00",
      "source_revision": "d1820256edccd0c7a6f53f35788f2511ecde9578",
      "availability": "current",
      "result": "clean",
      "counts": {
        "errors": 0,
        "warnings": 0,
        "findings": 0,
        "issue_pages": 64,
        "proposal_pages": 41
      }
    },
    "automation_summary": {
      "chain_id": "host-dispatch-20260726T024940Z",
      "status": "failed",
      "generated_at": "2026-07-26T02:49:40+00:00",
      "stage_count": 0
    },
    "publication_summary": {
      "disposition_counts": {
        "included": 138,
        "excluded": 209,
        "unclassified": 0,
        "conflict": 0
      },
      "build_count": 1,
      "topic_product_count": 5
    },
    "source_checker_summary": {
      "checked_at": "2026-07-24T14:14:17Z",
      "source_revision": null,
      "availability": "stale",
      "expected_count": 2055,
      "actual_count": 2048,
      "counts": {
        "access restricted": 772,
        "broken": 14,
        "identity mismatch": 3,
        "identity-preserving redirect": 95,
        "review required": 81,
        "transient failure": 9,
        "verified": 1074
      }
    }
  },
  "generation_manifest": {
    "manifest_schema_version": 1,
    "generation_id": "project-console-1d6aef983851e86dd50d",
    "generated_at": "2026-07-26T02:52:44+00:00",
    "source_revision": "d1820256edccd0c7a6f53f35788f2511ecde9578",
    "availability": "stale",
    "completeness": {
      "complete": false,
      "expected_count": 5639,
      "actual_count": 5639,
      "missing_count": 0
    },
    "domain_count": 40,
    "domains": [
      {
        "file": "automation.js",
        "sha256": "sha256:eebd377e5874f735663dc4a30fabd0503ff30d9da26be8b9ed05a1030184c664",
        "bytes": 242775,
        "keys": [
          "agent_registry",
          "run_chain"
        ],
        "record_count": 63
      },
      {
        "file": "candidates.js",
        "sha256": "sha256:03a6a23a94b04111fa0d5394b60a586b42cb43ace322c7ef9353c75e8d40614e",
        "bytes": 1417241,
        "keys": [
          "active_horizon_records",
          "horizon_records",
          "records"
        ],
        "record_count": 43
      },
      {
        "file": "directives-catalog-001.js",
        "sha256": "sha256:05ba5a09ad1fa9d8c529779970ac08de5bdd553bbb7e76245e54fa33fa76355b",
        "bytes": 197076,
        "keys": [
          "presidential_directives_chunk_001"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-002.js",
        "sha256": "sha256:f78d2e0035807dc243624472466d674ae375a19ddb75781c0774ea81628d86d1",
        "bytes": 191565,
        "keys": [
          "presidential_directives_chunk_002"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-003.js",
        "sha256": "sha256:5a6add0be6098703470e830949a854c995fa547fa83769b2128f2bea4f0ee12b",
        "bytes": 190597,
        "keys": [
          "presidential_directives_chunk_003"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-004.js",
        "sha256": "sha256:7fa2adefa8bfdfa17ce8161f517122e03ad512fbff945b6d5503bc629a1e07a3",
        "bytes": 191231,
        "keys": [
          "presidential_directives_chunk_004"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-005.js",
        "sha256": "sha256:3617d014fcd037747adb4e56e4a26cd9d10f6ae8dd71b2168575b82be4d0237c",
        "bytes": 190900,
        "keys": [
          "presidential_directives_chunk_005"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-006.js",
        "sha256": "sha256:1ae9f3f3db61947fb245d3bf4507f4358646c8207d578849a7aee14b24b83160",
        "bytes": 188556,
        "keys": [
          "presidential_directives_chunk_006"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-007.js",
        "sha256": "sha256:2ad445038fdcd482857a8b9f8a52f62d69e11b737d4856fbf4bae9ed24d1030f",
        "bytes": 189119,
        "keys": [
          "presidential_directives_chunk_007"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-008.js",
        "sha256": "sha256:cfe544afd1e56324c8ae5c1880bca1283981809386326ea06f65b088c319c03b",
        "bytes": 190582,
        "keys": [
          "presidential_directives_chunk_008"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-009.js",
        "sha256": "sha256:6947eea1c66fab959a7cd8b81f6dcaa0ec5f96c1c8c337ce57e037aa996cec22",
        "bytes": 188805,
        "keys": [
          "presidential_directives_chunk_009"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-010.js",
        "sha256": "sha256:2d44ce4c317e31441345b062fa04e4b088af2f304c824bc211b430eacd043bb1",
        "bytes": 189815,
        "keys": [
          "presidential_directives_chunk_010"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-011.js",
        "sha256": "sha256:0632e6d02bc15ed205f8204aaf2e890cf0de718f175c975085113236eab259f2",
        "bytes": 192216,
        "keys": [
          "presidential_directives_chunk_011"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-012.js",
        "sha256": "sha256:3e17ac4cd0d0fe02d775a76e412df6620f066501aa7bece517f53da2070e2260",
        "bytes": 192465,
        "keys": [
          "presidential_directives_chunk_012"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-013.js",
        "sha256": "sha256:9a0826d7a6ecff16049adb5b0207567f1e9e587e18cbd171f2a90069c5809bd6",
        "bytes": 188906,
        "keys": [
          "presidential_directives_chunk_013"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-014.js",
        "sha256": "sha256:448801a35f0ad72b8c34761d5c8798b0b1dfe65bbd76af67e41285fb50480462",
        "bytes": 190280,
        "keys": [
          "presidential_directives_chunk_014"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-015.js",
        "sha256": "sha256:3dc0f53e40c904b8754af69e56123b1c95ffbdc8d05167413a3c2fa821819f24",
        "bytes": 188808,
        "keys": [
          "presidential_directives_chunk_015"
        ],
        "record_count": 188
      },
      {
        "file": "directives-catalog-016.js",
        "sha256": "sha256:e0ec5e8908191d34870eeed8c3dc0a74d83214a07af13c2dda9ecced5881091c",
        "bytes": 187409,
        "keys": [
          "presidential_directives_chunk_016"
        ],
        "record_count": 187
      },
      {
        "file": "integrity.js",
        "sha256": "sha256:ef60e9d891ec5dd052f371d99add6e003eca2da5fb571ffffde3f349a36423cf",
        "bytes": 14131,
        "keys": [
          "integrity"
        ],
        "record_count": 53
      },
      {
        "file": "logs.js",
        "sha256": "sha256:fc0eb860475336cdaca2f7e5d4a4dce8e45947ad69cbaac72ad8105ff2bcb597",
        "bytes": 790884,
        "keys": [
          "project_logs",
          "repository_review_recommendations"
        ],
        "record_count": 7
      },
      {
        "file": "overview.js",
        "sha256": "sha256:bd192116e539c314d5774e784b279a8a7f3194096dee943cab588659974c6191",
        "bytes": 28416,
        "keys": [
          "overview"
        ],
        "record_count": 47
      },
      {
        "file": "progress.js",
        "sha256": "sha256:53c5da0da16e316571bed9e2542219a9ce9b681b54b9c771a7cdd69fe82db4c8",
        "bytes": 359286,
        "keys": [
          "progress"
        ],
        "record_count": 266
      },
      {
        "file": "publication.js",
        "sha256": "sha256:438e0cc00c744da5ba2f6e46918b66c8f7f83e1c77af43a2c5907a9954612762",
        "bytes": 666035,
        "keys": [
          "delivery_items",
          "page_inventory",
          "publication",
          "topic_products"
        ],
        "record_count": 717
      },
      {
        "file": "sources-catalog-001.js",
        "sha256": "sha256:c9dba841a570b3a82c2a3b61ae66f05e25259fb615042edd5e5bd0bb0acc065c",
        "bytes": 132073,
        "keys": [
          "cited_sources_chunk_001"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-002.js",
        "sha256": "sha256:72bc650c97f4f164c46e63cb45b479180552322d596f30b1bbf932ef113e5537",
        "bytes": 148337,
        "keys": [
          "cited_sources_chunk_002"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-003.js",
        "sha256": "sha256:aef857006e53d699a290ab85bcf213bf8440666a7bfd85c173e9f1dfa3e3d993",
        "bytes": 157274,
        "keys": [
          "cited_sources_chunk_003"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-004.js",
        "sha256": "sha256:ec8ff50cf035b077708303a0e4df916ef8708c97b691b27de33d22484c1381ef",
        "bytes": 161793,
        "keys": [
          "cited_sources_chunk_004"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-005.js",
        "sha256": "sha256:4e4ed915c063be2eb30107c1c9b13d674bbbe588ee1919506d0a17b1809239b2",
        "bytes": 147692,
        "keys": [
          "cited_sources_chunk_005"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-006.js",
        "sha256": "sha256:a2039a73481349212463ea7f642d0c022b6d847a05962ae1d995245ca3b3c909",
        "bytes": 175125,
        "keys": [
          "cited_sources_chunk_006"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-007.js",
        "sha256": "sha256:a9459b9f507fcd0fa7e11a2d19519d7f395ae9d94e08aeb6c10ef0e0447f272a",
        "bytes": 194692,
        "keys": [
          "cited_sources_chunk_007"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-008.js",
        "sha256": "sha256:16b987b52ec994b2cd911f1b2bd6bf2f09b92db1eb68026442633ae97f921f2d",
        "bytes": 165787,
        "keys": [
          "cited_sources_chunk_008"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-009.js",
        "sha256": "sha256:6734c22a895f2541a61b58bb7872633d8d13d066b6276ce2e1c71ba7e5781cd8",
        "bytes": 158635,
        "keys": [
          "cited_sources_chunk_009"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-010.js",
        "sha256": "sha256:ecf67f7c351524ed404364a00213dfac1ea4befa216b741b1290fd3fc54c20f8",
        "bytes": 179908,
        "keys": [
          "cited_sources_chunk_010"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-011.js",
        "sha256": "sha256:26e9cc6d582629cda7cdb3bd95c71641618c2a5d9c81ae2eb3a8b1487857f890",
        "bytes": 185734,
        "keys": [
          "cited_sources_chunk_011"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-012.js",
        "sha256": "sha256:fe8d39510d10c9446a4c7f5450ae3e76895ce65f469594e5f50c7dc0aa050d2f",
        "bytes": 189916,
        "keys": [
          "cited_sources_chunk_012"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-013.js",
        "sha256": "sha256:4992ee00bfebf27e10337a17529a50fd7306718e9e1fa5259824b60f553d9eb1",
        "bytes": 184382,
        "keys": [
          "cited_sources_chunk_013"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-014.js",
        "sha256": "sha256:e9817ad8d038a366bab1933dda5ae67b0e9bcc8b9d84a4e23880345d5aabd05c",
        "bytes": 177061,
        "keys": [
          "cited_sources_chunk_014"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-015.js",
        "sha256": "sha256:3764e8f40113d622d181306a10b4b78df0e471be7d3126a4260ca373439e2d54",
        "bytes": 177535,
        "keys": [
          "cited_sources_chunk_015"
        ],
        "record_count": 129
      },
      {
        "file": "sources-catalog-016.js",
        "sha256": "sha256:f708075e826e2b600ef08298f1a2dfaf6a9cdc588e54ccd222a2ab53ab6d2abd",
        "bytes": 149384,
        "keys": [
          "cited_sources_chunk_016"
        ],
        "record_count": 120
      },
      {
        "file": "sources.js",
        "sha256": "sha256:88c8400ee71908eefd621f0efb2da55811f1ba5db1f822cf734c3dc9ab793e49",
        "bytes": 3677787,
        "keys": [
          "cited_sources",
          "court_watch_sources",
          "monitoring_issues",
          "pending_sources",
          "presidential_directives",
          "source_checker",
          "watcher_metadata"
        ],
        "record_count": 2606
      }
    ],
    "files": {
      "automation.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:eebd377e5874f735663dc4a30fabd0503ff30d9da26be8b9ed05a1030184c664",
        "bytes": 242775,
        "keys": [
          "agent_registry",
          "run_chain"
        ],
        "record_count": 63
      },
      "candidates.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:03a6a23a94b04111fa0d5394b60a586b42cb43ace322c7ef9353c75e8d40614e",
        "bytes": 1417241,
        "keys": [
          "active_horizon_records",
          "horizon_records",
          "records"
        ],
        "record_count": 43
      },
      "directives-catalog-001.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:05ba5a09ad1fa9d8c529779970ac08de5bdd553bbb7e76245e54fa33fa76355b",
        "bytes": 197076,
        "keys": [
          "presidential_directives_chunk_001"
        ],
        "record_count": 188
      },
      "directives-catalog-002.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:f78d2e0035807dc243624472466d674ae375a19ddb75781c0774ea81628d86d1",
        "bytes": 191565,
        "keys": [
          "presidential_directives_chunk_002"
        ],
        "record_count": 188
      },
      "directives-catalog-003.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:5a6add0be6098703470e830949a854c995fa547fa83769b2128f2bea4f0ee12b",
        "bytes": 190597,
        "keys": [
          "presidential_directives_chunk_003"
        ],
        "record_count": 188
      },
      "directives-catalog-004.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:7fa2adefa8bfdfa17ce8161f517122e03ad512fbff945b6d5503bc629a1e07a3",
        "bytes": 191231,
        "keys": [
          "presidential_directives_chunk_004"
        ],
        "record_count": 188
      },
      "directives-catalog-005.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:3617d014fcd037747adb4e56e4a26cd9d10f6ae8dd71b2168575b82be4d0237c",
        "bytes": 190900,
        "keys": [
          "presidential_directives_chunk_005"
        ],
        "record_count": 188
      },
      "directives-catalog-006.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:1ae9f3f3db61947fb245d3bf4507f4358646c8207d578849a7aee14b24b83160",
        "bytes": 188556,
        "keys": [
          "presidential_directives_chunk_006"
        ],
        "record_count": 188
      },
      "directives-catalog-007.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:2ad445038fdcd482857a8b9f8a52f62d69e11b737d4856fbf4bae9ed24d1030f",
        "bytes": 189119,
        "keys": [
          "presidential_directives_chunk_007"
        ],
        "record_count": 188
      },
      "directives-catalog-008.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:cfe544afd1e56324c8ae5c1880bca1283981809386326ea06f65b088c319c03b",
        "bytes": 190582,
        "keys": [
          "presidential_directives_chunk_008"
        ],
        "record_count": 188
      },
      "directives-catalog-009.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:6947eea1c66fab959a7cd8b81f6dcaa0ec5f96c1c8c337ce57e037aa996cec22",
        "bytes": 188805,
        "keys": [
          "presidential_directives_chunk_009"
        ],
        "record_count": 188
      },
      "directives-catalog-010.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:2d44ce4c317e31441345b062fa04e4b088af2f304c824bc211b430eacd043bb1",
        "bytes": 189815,
        "keys": [
          "presidential_directives_chunk_010"
        ],
        "record_count": 188
      },
      "directives-catalog-011.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:0632e6d02bc15ed205f8204aaf2e890cf0de718f175c975085113236eab259f2",
        "bytes": 192216,
        "keys": [
          "presidential_directives_chunk_011"
        ],
        "record_count": 188
      },
      "directives-catalog-012.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:3e17ac4cd0d0fe02d775a76e412df6620f066501aa7bece517f53da2070e2260",
        "bytes": 192465,
        "keys": [
          "presidential_directives_chunk_012"
        ],
        "record_count": 188
      },
      "directives-catalog-013.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:9a0826d7a6ecff16049adb5b0207567f1e9e587e18cbd171f2a90069c5809bd6",
        "bytes": 188906,
        "keys": [
          "presidential_directives_chunk_013"
        ],
        "record_count": 188
      },
      "directives-catalog-014.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:448801a35f0ad72b8c34761d5c8798b0b1dfe65bbd76af67e41285fb50480462",
        "bytes": 190280,
        "keys": [
          "presidential_directives_chunk_014"
        ],
        "record_count": 188
      },
      "directives-catalog-015.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:3dc0f53e40c904b8754af69e56123b1c95ffbdc8d05167413a3c2fa821819f24",
        "bytes": 188808,
        "keys": [
          "presidential_directives_chunk_015"
        ],
        "record_count": 188
      },
      "directives-catalog-016.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:e0ec5e8908191d34870eeed8c3dc0a74d83214a07af13c2dda9ecced5881091c",
        "bytes": 187409,
        "keys": [
          "presidential_directives_chunk_016"
        ],
        "record_count": 187
      },
      "integrity.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:ef60e9d891ec5dd052f371d99add6e003eca2da5fb571ffffde3f349a36423cf",
        "bytes": 14131,
        "keys": [
          "integrity"
        ],
        "record_count": 53
      },
      "logs.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:fc0eb860475336cdaca2f7e5d4a4dce8e45947ad69cbaac72ad8105ff2bcb597",
        "bytes": 790884,
        "keys": [
          "project_logs",
          "repository_review_recommendations"
        ],
        "record_count": 7
      },
      "overview.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:bd192116e539c314d5774e784b279a8a7f3194096dee943cab588659974c6191",
        "bytes": 28416,
        "keys": [
          "overview"
        ],
        "record_count": 47
      },
      "progress.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:53c5da0da16e316571bed9e2542219a9ce9b681b54b9c771a7cdd69fe82db4c8",
        "bytes": 359286,
        "keys": [
          "progress"
        ],
        "record_count": 266
      },
      "publication.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:438e0cc00c744da5ba2f6e46918b66c8f7f83e1c77af43a2c5907a9954612762",
        "bytes": 666035,
        "keys": [
          "delivery_items",
          "page_inventory",
          "publication",
          "topic_products"
        ],
        "record_count": 717
      },
      "sources-catalog-001.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:c9dba841a570b3a82c2a3b61ae66f05e25259fb615042edd5e5bd0bb0acc065c",
        "bytes": 132073,
        "keys": [
          "cited_sources_chunk_001"
        ],
        "record_count": 129
      },
      "sources-catalog-002.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:72bc650c97f4f164c46e63cb45b479180552322d596f30b1bbf932ef113e5537",
        "bytes": 148337,
        "keys": [
          "cited_sources_chunk_002"
        ],
        "record_count": 129
      },
      "sources-catalog-003.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:aef857006e53d699a290ab85bcf213bf8440666a7bfd85c173e9f1dfa3e3d993",
        "bytes": 157274,
        "keys": [
          "cited_sources_chunk_003"
        ],
        "record_count": 129
      },
      "sources-catalog-004.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:ec8ff50cf035b077708303a0e4df916ef8708c97b691b27de33d22484c1381ef",
        "bytes": 161793,
        "keys": [
          "cited_sources_chunk_004"
        ],
        "record_count": 129
      },
      "sources-catalog-005.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:4e4ed915c063be2eb30107c1c9b13d674bbbe588ee1919506d0a17b1809239b2",
        "bytes": 147692,
        "keys": [
          "cited_sources_chunk_005"
        ],
        "record_count": 129
      },
      "sources-catalog-006.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:a2039a73481349212463ea7f642d0c022b6d847a05962ae1d995245ca3b3c909",
        "bytes": 175125,
        "keys": [
          "cited_sources_chunk_006"
        ],
        "record_count": 129
      },
      "sources-catalog-007.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:a9459b9f507fcd0fa7e11a2d19519d7f395ae9d94e08aeb6c10ef0e0447f272a",
        "bytes": 194692,
        "keys": [
          "cited_sources_chunk_007"
        ],
        "record_count": 129
      },
      "sources-catalog-008.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:16b987b52ec994b2cd911f1b2bd6bf2f09b92db1eb68026442633ae97f921f2d",
        "bytes": 165787,
        "keys": [
          "cited_sources_chunk_008"
        ],
        "record_count": 129
      },
      "sources-catalog-009.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:6734c22a895f2541a61b58bb7872633d8d13d066b6276ce2e1c71ba7e5781cd8",
        "bytes": 158635,
        "keys": [
          "cited_sources_chunk_009"
        ],
        "record_count": 129
      },
      "sources-catalog-010.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:ecf67f7c351524ed404364a00213dfac1ea4befa216b741b1290fd3fc54c20f8",
        "bytes": 179908,
        "keys": [
          "cited_sources_chunk_010"
        ],
        "record_count": 129
      },
      "sources-catalog-011.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:26e9cc6d582629cda7cdb3bd95c71641618c2a5d9c81ae2eb3a8b1487857f890",
        "bytes": 185734,
        "keys": [
          "cited_sources_chunk_011"
        ],
        "record_count": 129
      },
      "sources-catalog-012.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:fe8d39510d10c9446a4c7f5450ae3e76895ce65f469594e5f50c7dc0aa050d2f",
        "bytes": 189916,
        "keys": [
          "cited_sources_chunk_012"
        ],
        "record_count": 129
      },
      "sources-catalog-013.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:4992ee00bfebf27e10337a17529a50fd7306718e9e1fa5259824b60f553d9eb1",
        "bytes": 184382,
        "keys": [
          "cited_sources_chunk_013"
        ],
        "record_count": 129
      },
      "sources-catalog-014.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:e9817ad8d038a366bab1933dda5ae67b0e9bcc8b9d84a4e23880345d5aabd05c",
        "bytes": 177061,
        "keys": [
          "cited_sources_chunk_014"
        ],
        "record_count": 129
      },
      "sources-catalog-015.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:3764e8f40113d622d181306a10b4b78df0e471be7d3126a4260ca373439e2d54",
        "bytes": 177535,
        "keys": [
          "cited_sources_chunk_015"
        ],
        "record_count": 129
      },
      "sources-catalog-016.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:f708075e826e2b600ef08298f1a2dfaf6a9cdc588e54ccd222a2ab53ab6d2abd",
        "bytes": 149384,
        "keys": [
          "cited_sources_chunk_016"
        ],
        "record_count": 120
      },
      "sources.js": {
        "generation_id": "project-console-1d6aef983851e86dd50d",
        "sha256": "sha256:88c8400ee71908eefd621f0efb2da55811f1ba5db1f822cf734c3dc9ab793e49",
        "bytes": 3677787,
        "keys": [
          "cited_sources",
          "court_watch_sources",
          "monitoring_issues",
          "pending_sources",
          "presidential_directives",
          "source_checker",
          "watcher_metadata"
        ],
        "record_count": 2606
      }
    }
  }
};
