#!/usr/bin/env python3
"""Build the preliminary-candidate-only ARRP Horizon review console."""

from __future__ import annotations

import csv
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CANDIDATES = ROOT / "research" / "trump-administration-preliminary-candidates.csv"
ROUTING = ROOT / "research" / "trump-administration-evidence-routing.csv"
CATALOG = ROOT / "research" / "trump-administration-legal-review-catalog.csv"
MEDIA = ROOT / "research" / "trump-administration-media-review-intake.csv"
OUTPUT = ROOT / "research" / "horizon-review-console" / "catalog-data.js"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def parse_links(raw: str) -> list[dict[str, str]]:
    links: list[dict[str, str]] = []
    for item in raw.split("||"):
        item = item.strip()
        if not item or "|" not in item:
            continue
        label, url = item.split("|", 1)
        if label.strip() and url.strip():
            links.append({"label": label.strip(), "url": url.strip()})
    return links


def candidate_records(routing: list[dict[str, str]]) -> list[dict[str, object]]:
    evidence_ids: dict[str, list[str]] = {}
    for item in routing:
        candidate_id = item["candidate_id"].strip()
        if candidate_id:
            evidence_ids.setdefault(candidate_id, []).append(item["catalog_id"])
    records: list[dict[str, object]] = []
    for row in read_csv(CANDIDATES):
        if row["review_status"] != "preliminary-candidate":
            continue
        attached_ids = evidence_ids.get(row["candidate_id"], [])
        explicit_ids = [item.strip() for item in row["source_record_ids"].split(";") if item.strip()]
        combined_ids = list(dict.fromkeys([*explicit_ids, *attached_ids]))
        records.append(
            {
                "id": row["candidate_id"],
                "horizon_id": row["horizon_id"],
                "kind": "preliminary_candidate",
                "title": row["title"],
                "term": row["term"],
                "category": "preliminary institutional question",
                "summary": row["institutional_defect"],
                "review_prompt": "Should this preliminary candidate be promoted to a formal HOR candidate?",
                "proposed_area": row["proposed_area"],
                "distinctness": row["distinctness_rationale"],
                "coverage": row["existing_coverage_considered"],
                "counterargument": row["counterargument"],
                "unresolved": row["unresolved_questions"],
                "recommendation": row["recommendation"],
                "source_record_ids": "; ".join(combined_ids),
                "links": parse_links(row["source_links"]),
                "review_status": row["review_status"],
                "last_checked": row["last_reviewed"],
            }
        )
    return records


def main() -> None:
    routing = read_csv(ROUTING)
    candidates = candidate_records(routing)
    routing_counts = Counter(row["disposition"] for row in routing)
    payload = {
        "schema_version": 2,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "candidate_source": CANDIDATES.name,
        "candidate_questions": len(candidates),
        "evidence_records": len(routing),
        "existing_issue_queue": routing_counts["existing-record-integration"],
        "preliminary_candidate_evidence": routing_counts["preliminary-candidate-evidence"],
        "agent_review_pending": routing_counts["agent-review-needed"],
        "retained_research": routing_counts["research-retained-no-current-route"],
        "media_episodes": len(read_csv(MEDIA)),
        "catalog_records": len(read_csv(CATALOG)),
        "records": candidates,
    }
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    serialized = serialized.replace("</", "<\\/")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "/* Generated by scripts/build_horizon_review_console.py. */\n"
        f"window.ARRP_HORIZON_REVIEW_DATA={serialized};\n",
        encoding="utf-8",
    )
    print(
        f"Wrote {OUTPUT.relative_to(ROOT)} with {len(candidates)} preliminary candidates; "
        f"the {len(routing):,} source records remain in the separate evidence-routing ledger."
    )


if __name__ == "__main__":
    main()
