#!/usr/bin/env python3
"""Build one immutable, owner-only Project Console snapshot.

The repository contains the single Console implementation.  This script
validates that implementation's current public data generation, minimizes and
binds the three ignored local projections, and stages a self-contained static
snapshot through an owner-only inactive staging descriptor.

It does not activate a runtime, change host state, read a credential, perform
network access, or modify the source Console.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

try:
    from github_disclosure_gate import prohibited_secret_findings
    from path_authority import (
        APPROVED_REPOSITORY_ROOT,
        PrivateProjectAuthority,
    )
except ModuleNotFoundError:
    from scripts.github_disclosure_gate import prohibited_secret_findings
    from scripts.path_authority import (
        APPROVED_REPOSITORY_ROOT,
        PrivateProjectAuthority,
    )


PUBLIC_CONSOLE_RELATIVE = Path("research/horizon-review-console")
PUBLIC_SHELL_FILES = (
    "index.html",
    "styles.css",
    "app.js",
    "catalog-data.js",
)
PRIVATE_PROJECTION_SPECS = {
    "security-assurance": (
        "private-security-assurance.js",
        "window.ARRP_PRIVATE_SECURITY_ASSURANCE=",
        "/* Private local projection; never commit or publish. */\n",
    ),
    "private-operations": (
        "private-operations.js",
        "window.ARRP_PRIVATE_OPERATIONS=",
        "/* Private local projection; never commit or publish. */\n",
    ),
    "local-automation-status": (
        "local-automation-status.js",
        "window.ARRP_LOCAL_AUTOMATION_STATUS = ",
        "",
    ),
}
PRIVATE_GLOBALS = {
    "security-assurance": "window.ARRP_PRIVATE_SECURITY_ASSURANCE",
    "private-operations": "window.ARRP_PRIVATE_OPERATIONS",
    "local-automation-status": "window.ARRP_LOCAL_AUTOMATION_STATUS",
}
CATALOG_PREFIX = (
    "/* Generated by scripts/build_horizon_review_console.py. */\n"
    "window.ARRP_HORIZON_REVIEW_DATA="
)
PART_PREFIX = (
    "/* Generated by scripts/build_horizon_review_console.py. */\n"
    "window.ARRP_HORIZON_REVIEW_DATA=window.ARRP_HORIZON_REVIEW_DATA||{};\n"
    "Object.assign(window.ARRP_HORIZON_REVIEW_DATA,"
)
OWNER_BINDING_GLOBAL = "window.ARRP_OWNER_CONSOLE_BINDING"
OWNER_BINDING_FILE = "owner-console-binding.js"
GENERATION_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
SOURCE_REVISION_PATTERN = re.compile(r"^[0-9a-f]{40}(?:[0-9a-f]{24})?$")
SHA256_PATTERN = re.compile(r"^sha256:[0-9a-f]{64}$")
STATUS_VALUES = frozenset(
    {
        "completed",
        "review-required",
        "failed",
        "blocked",
        "usage-stopped",
        "missed",
        "running",
    }
)
LOCAL_STATUS_FIELDS = frozenset(
    {
        "schema_version",
        "run_id",
        "trigger",
        "scheduled_for",
        "started_at",
        "updated_at",
        "completed_at",
        "status",
        "control_state",
        "control_state_checked_at",
        "stage",
        "canonical_path",
        "starting_branch",
        "starting_local_head",
        "fetched_origin_main",
        "preexisting_path_manifest_sha256",
        "checkpoint_commit",
        "nightly_branch",
        "worktree_path",
        "runtime_commit",
        "elim_unit",
        "elim_outcome",
        "validation_summary",
        "classification",
        "pull_request",
        "expected_pr_head",
        "merge_commit",
        "project_sync",
        "pages_workflow_run",
        "pages_conclusion",
        "preserved_paths",
        "failure_class",
        "failure_reason",
        "exact_next_action",
    }
)
SECURITY_TOP_FIELDS = frozenset(
    {
        "schema_version",
        "availability",
        "complete",
        "checked_at",
        "public_intake_state",
        "private_attention",
        "active_incident",
        "tools",
    }
)
SECURITY_TOOL_FIELDS = frozenset(
    {
        "tool_id",
        "label",
        "availability",
        "last_checked",
        "next_due",
        "source_revision",
        "coverage_state",
        "private_attention",
        "owner_class",
        "destination_class",
        "active_incident",
        "public_intake_state",
    }
)
PRIVATE_OPERATIONS_FIELDS = frozenset(
    {
        "schema_version",
        "availability",
        "generated_at",
        "catalog_generation_id",
        "source_revision",
        "agent_registry",
        "project_logs",
        "integrity",
        "run_chain",
        "action_snapshot",
        "queue_directory",
        "operational_incidents",
        "security_incidents",
        "incident_relations",
        "governance_change_supplements",
        "privacy",
    }
)
GOVERNANCE_SUPPLEMENT_PROJECTION_FIELDS = frozenset(
    {
        "schema_version",
        "availability",
        "complete",
        "checked_at",
        "source_revision",
        "public_log_sha256",
        "items",
        "reason_code",
    }
)
GOVERNANCE_SUPPLEMENT_ITEM_FIELDS = frozenset(
    {
        "governance_change_id",
        "public_entry_sha256",
        "source_revision",
        "recorded_at",
        "safe_summary",
    }
)
SECURITY_INCIDENT_ITEM_FIELDS = frozenset(
    {
        "security_incident_id",
        "identity_key",
        "security_domain",
        "protected_surface",
        "event_class",
        "safe_summary",
        "status",
        "reported_by",
        "owner",
        "recommended_owner",
        "next_action",
        "first_observed",
        "last_observed",
        "occurrences",
        "restricted_evidence_refs",
        "closure_evidence",
        "events",
        "prior_security_incident_id",
    }
)
SECURITY_INCIDENT_OCCURRENCE_FIELDS = frozenset(
    {"occurrence_id", "observed_at", "source_ref", "safe_observation"}
)
SECURITY_INCIDENT_CLOSURE_FIELDS = frozenset(
    {
        "verified_at",
        "disposition_code",
        "closure_test",
        "result",
        "recorded_by",
        "restricted_evidence_refs",
    }
)
SECURITY_INCIDENT_EVENT_FIELDS = frozenset(
    {
        "schema_version",
        "event_id",
        "security_incident_id",
        "event_type",
        "recorded_at",
        "identity_key",
        "security_domain",
        "protected_surface",
        "event_class",
        "safe_summary",
        "status",
        "reported_by",
        "owner",
        "recommended_owner",
        "next_action",
        "occurrence",
        "restricted_evidence_refs",
        "closure",
        "prior_security_incident_id",
        "event_sha256",
    }
)


class OwnerConsoleBuildError(RuntimeError):
    """Raised when no complete immutable owner snapshot can be produced."""


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _iso_utc(value: datetime) -> str:
    normalized = value.astimezone(timezone.utc)
    return normalized.isoformat(timespec="microseconds").replace("+00:00", "Z")


def _version_timestamp(value: datetime) -> str:
    return value.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")


def _parsed_timestamp(value: object) -> datetime | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return None
    return parsed.astimezone(timezone.utc)


def _sha256(content: bytes) -> str:
    return "sha256:" + hashlib.sha256(content).hexdigest()


def _read_regular(path: Path, *, owner_only: bool) -> bytes:
    try:
        before = path.lstat()
    except OSError as error:
        raise OwnerConsoleBuildError(
            f"required Console source is unavailable: {path.name}"
        ) from error
    if stat.S_ISLNK(before.st_mode) or not stat.S_ISREG(before.st_mode):
        raise OwnerConsoleBuildError(
            f"Console source must be a regular non-symlink: {path.name}"
        )
    if before.st_uid != os.getuid():
        raise OwnerConsoleBuildError(
            f"Console source has an unexpected owner: {path.name}"
        )
    if owner_only and stat.S_IMODE(before.st_mode) & 0o077:
        raise OwnerConsoleBuildError(
            f"private Console source is not owner-only: {path.name}"
        )
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise OwnerConsoleBuildError(
            f"Console source could not be opened safely: {path.name}"
        ) from error
    try:
        opened = os.fstat(descriptor)
        if (
            not stat.S_ISREG(opened.st_mode)
            or opened.st_dev != before.st_dev
            or opened.st_ino != before.st_ino
        ):
            raise OwnerConsoleBuildError(
                f"Console source identity changed during read: {path.name}"
            )
        chunks: list[bytes] = []
        while True:
            block = os.read(descriptor, 1024 * 1024)
            if not block:
                break
            chunks.append(block)
        return b"".join(chunks)
    finally:
        os.close(descriptor)


def _json_script_payload(
    content: bytes,
    *,
    prefix: str,
    leading_comment: str = "",
    suffix: str = ";\n",
) -> dict[str, Any]:
    try:
        text = content.decode("utf-8")
    except UnicodeError as error:
        raise OwnerConsoleBuildError(
            "Console projection is not valid UTF-8"
        ) from error
    if leading_comment and not text.startswith(leading_comment):
        raise OwnerConsoleBuildError(
            "private Console projection has an invalid header"
        )
    body = text.removeprefix(leading_comment)
    if not body.startswith(prefix) or not body.endswith(suffix):
        raise OwnerConsoleBuildError(
            "Console projection has an invalid assignment envelope"
        )
    try:
        value = json.loads(body.removeprefix(prefix).removesuffix(suffix))
    except json.JSONDecodeError as error:
        raise OwnerConsoleBuildError(
            "Console projection contains invalid JSON"
        ) from error
    if not isinstance(value, dict):
        raise OwnerConsoleBuildError(
            "Console projection payload must be an object"
        )
    return value


def _validate_manifest(
    manifest: Mapping[str, Any],
    *,
    data_dir: Path,
) -> tuple[str, str, dict[str, bytes]]:
    generation_id = str(manifest.get("generation_id") or "")
    source_revision = str(manifest.get("source_revision") or "")
    completeness = manifest.get("completeness")
    if not GENERATION_ID_PATTERN.fullmatch(generation_id):
        raise OwnerConsoleBuildError(
            "public Console manifest has an unsafe generation identity"
        )
    if not SOURCE_REVISION_PATTERN.fullmatch(source_revision):
        raise OwnerConsoleBuildError(
            "public Console manifest lacks an exact source revision"
        )
    if manifest.get("availability") != "current":
        raise OwnerConsoleBuildError(
            "public Console generation is not current"
        )
    if not isinstance(completeness, dict) or set(completeness) != {
        "actual_count",
        "complete",
        "expected_count",
        "missing_count",
    }:
        raise OwnerConsoleBuildError(
            "public Console completeness evidence is malformed"
        )
    if (
        completeness.get("complete") is not True
        or not isinstance(completeness.get("actual_count"), int)
        or not isinstance(completeness.get("expected_count"), int)
        or completeness["actual_count"] != completeness["expected_count"]
        or completeness.get("missing_count") != 0
    ):
        raise OwnerConsoleBuildError(
            "public Console generation is incomplete"
        )
    files = manifest.get("files")
    domains = manifest.get("domains")
    if (
        not isinstance(files, dict)
        or not files
        or not isinstance(domains, list)
        or manifest.get("domain_count") != len(files)
        or len(domains) != len(files)
    ):
        raise OwnerConsoleBuildError(
            "public Console domain inventory is incomplete"
        )
    domain_by_name: dict[str, Mapping[str, Any]] = {}
    for row in domains:
        if not isinstance(row, dict):
            raise OwnerConsoleBuildError(
                "public Console domain record is malformed"
            )
        name = str(row.get("file") or "")
        if (
            not name
            or Path(name).name != name
            or not name.endswith(".js")
            or name in domain_by_name
        ):
            raise OwnerConsoleBuildError(
                "public Console domain name is unsafe"
            )
        domain_by_name[name] = row
    if set(domain_by_name) != set(files):
        raise OwnerConsoleBuildError(
            "public Console domain inventories disagree"
        )
    allowed_unmanifested = {
        "generation-manifest.json",
        *(spec[0] for spec in PRIVATE_PROJECTION_SPECS.values()),
    }
    observed = {
        path.name
        for path in data_dir.iterdir()
        if path.is_file() or path.is_symlink()
    }
    unexpected = observed - set(files) - allowed_unmanifested
    if unexpected:
        raise OwnerConsoleBuildError(
            "public Console data directory contains an unmanifested domain"
        )
    domain_contents: dict[str, bytes] = {}
    for name, raw_metadata in files.items():
        if not isinstance(raw_metadata, dict):
            raise OwnerConsoleBuildError(
                "public Console file metadata is malformed"
            )
        metadata = dict(raw_metadata)
        row = domain_by_name[name]
        if (
            metadata.get("generation_id") != generation_id
            or metadata.get("sha256") != row.get("sha256")
            or metadata.get("bytes") != row.get("bytes")
            or metadata.get("keys") != row.get("keys")
            or metadata.get("record_count") != row.get("record_count")
            or not SHA256_PATTERN.fullmatch(
                str(metadata.get("sha256") or "")
            )
        ):
            raise OwnerConsoleBuildError(
                f"public Console metadata disagrees for {name}"
            )
        content = _read_regular(data_dir / name, owner_only=False)
        if len(content) != metadata["bytes"] or _sha256(content) != metadata["sha256"]:
            raise OwnerConsoleBuildError(
                f"public Console hash verification failed for {name}"
            )
        part = _json_script_payload(
            content,
            prefix=PART_PREFIX,
            suffix=");\n",
        )
        domain_generation = part.get("domain_generation")
        if (
            not isinstance(domain_generation, dict)
            or domain_generation.get(name) != generation_id
        ):
            raise OwnerConsoleBuildError(
                f"public Console domain has a stale generation: {name}"
            )
        domain_contents[name] = content
    return generation_id, source_revision, domain_contents


def _validate_catalog(
    content: bytes,
    *,
    manifest: Mapping[str, Any],
    generation_id: str,
    source_revision: str,
) -> dict[str, Any]:
    catalog = _json_script_payload(content, prefix=CATALOG_PREFIX)
    if (
        catalog.get("generation_id") != generation_id
        or catalog.get("source_revision") != source_revision
        or catalog.get("generation_manifest") != manifest
    ):
        raise OwnerConsoleBuildError(
            "public Console catalog and generation manifest disagree"
        )
    return catalog


def _validate_security(
    payload: Mapping[str, Any],
    *,
    catalog: Mapping[str, Any],
) -> tuple[str, bool]:
    if set(payload) != SECURITY_TOP_FIELDS:
        raise OwnerConsoleBuildError(
            "private Security projection violates its top-level allowlist"
        )
    if (
        payload.get("schema_version") != 2
        or payload.get("availability") not in {"current", "unavailable"}
        or not isinstance(payload.get("complete"), bool)
        or payload.get("public_intake_state")
        not in {"live", "paused", "unverified"}
        or payload.get("private_attention")
        not in {"required", "none_reported", "unavailable"}
        or not isinstance(payload.get("active_incident"), bool)
        or not isinstance(payload.get("tools"), list)
    ):
        raise OwnerConsoleBuildError(
            "private Security projection has an invalid status contract"
        )
    availability = str(payload["availability"])
    complete = payload["complete"] is True
    if availability == "current":
        if not complete or _parsed_timestamp(payload.get("checked_at")) is None:
            raise OwnerConsoleBuildError(
                "current private Security projection is incomplete"
            )
    elif complete:
        raise OwnerConsoleBuildError(
            "unavailable private Security projection cannot be complete"
        )
    public_security = catalog.get("security_assurance")
    public_tools = (
        public_security.get("tools")
        if isinstance(public_security, dict)
        else None
    )
    if not isinstance(public_tools, list):
        raise OwnerConsoleBuildError(
            "public Security tool registry projection is unavailable"
        )
    definitions = {
        str(tool.get("tool_id") or ""): tool
        for tool in public_tools
        if isinstance(tool, dict)
    }
    observed: set[str] = set()
    for tool in payload["tools"]:
        if not isinstance(tool, dict) or set(tool) != SECURITY_TOOL_FIELDS:
            raise OwnerConsoleBuildError(
                "private Security tool violates its field allowlist"
            )
        tool_id = str(tool.get("tool_id") or "")
        definition = definitions.get(tool_id)
        if (
            not tool_id
            or tool_id in observed
            or definition is None
            or tool.get("label") != definition.get("label")
            or tool.get("owner_class") != definition.get("owner_class")
            or tool.get("destination_class")
            != definition.get("destination_class")
            or tool.get("availability") not in {"current", "unavailable"}
            or tool.get("coverage_state")
            not in {"current", "stale", "incomplete", "unavailable"}
            or tool.get("private_attention") not in {"yes", "no", "unknown"}
            or not isinstance(tool.get("active_incident"), bool)
            or tool.get("public_intake_state")
            not in {None, "live", "paused", "unverified"}
        ):
            raise OwnerConsoleBuildError(
                "private Security tool does not match its public definition"
            )
        observed.add(tool_id)
    if observed != set(definitions):
        raise OwnerConsoleBuildError(
            "private Security tool coverage is incomplete"
        )
    return availability, complete


def _exact_action_counts(items: list[object]) -> dict[str, int] | None:
    typed = [item for item in items if isinstance(item, dict)]
    if len(typed) != len(items):
        return None
    identities = [str(item.get("item_id") or "") for item in typed]
    if any(not identity for identity in identities) or len(identities) != len(
        set(identities)
    ):
        return None
    human = sum(
        item.get("attention_class") == "human" for item in typed
    )
    return {
        "human": human,
        "oversight": len(typed) - human,
        "all_open": len(typed),
    }


def _valid_action_snapshot(snapshot: Mapping[str, Any]) -> bool:
    required = {
        "schema_version",
        "generation_id",
        "generated_at",
        "availability",
        "complete",
        "items",
        "counts",
        "known_counts",
        "sources",
        "predicates",
    }
    allowed = required | {"private_join"}
    items = snapshot.get("items")
    if (
        not required <= set(snapshot) <= allowed
        or snapshot.get("schema_version") != 1
        or snapshot.get("availability") not in {"current", "partial"}
        or not isinstance(snapshot.get("complete"), bool)
        or not isinstance(items, list)
        or not isinstance(snapshot.get("counts"), dict)
        or not isinstance(snapshot.get("known_counts"), dict)
        or not isinstance(snapshot.get("sources"), dict)
        or not isinstance(snapshot.get("predicates"), dict)
        or _parsed_timestamp(snapshot.get("generated_at")) is None
    ):
        return False
    exact = _exact_action_counts(items)
    if exact is None or snapshot.get("known_counts") != exact:
        return False
    complete = snapshot["complete"] is True
    if complete:
        return (
            snapshot.get("availability") == "current"
            and snapshot.get("counts") == exact
        )
    return (
        snapshot.get("availability") == "partial"
        and snapshot.get("counts")
        == {"human": None, "oversight": None, "all_open": None}
    )


def _valid_queue_directory(directory: Mapping[str, Any]) -> bool:
    if set(directory) != {
        "schema_version",
        "generation_id",
        "generated_at",
        "availability",
        "complete",
        "queues",
    }:
        return False
    queues = directory.get("queues")
    if (
        directory.get("schema_version") != 1
        or directory.get("availability") not in {"current", "partial"}
        or not isinstance(directory.get("complete"), bool)
        or not isinstance(queues, list)
        or _parsed_timestamp(directory.get("generated_at")) is None
    ):
        return False
    identifiers: set[str] = set()
    for queue in queues:
        if not isinstance(queue, dict):
            return False
        queue_id = str(queue.get("queue_id") or "")
        complete = queue.get("complete") is True
        if (
            not queue_id
            or queue_id in identifiers
            or not isinstance(queue.get("complete"), bool)
            or queue.get("availability")
            != ("current" if complete else "unavailable")
            or (
                complete
                and (
                    not isinstance(queue.get("count"), int)
                    or isinstance(queue.get("count"), bool)
                    or queue["count"] < 0
                )
            )
            or (not complete and queue.get("count") is not None)
        ):
            return False
        identifiers.add(queue_id)
    all_complete = all(
        isinstance(queue, dict) and queue.get("complete") is True
        for queue in queues
    )
    return (
        directory.get("complete") is all_complete
        and directory.get("availability")
        == ("current" if all_complete else "partial")
    )


def _valid_incident_projection(
    projection: Mapping[str, Any],
    *,
    incident_kind: str,
) -> bool:
    items = projection.get("items")
    complete = projection.get("complete") is True
    if (
        projection.get("schema_version") != 1
        or projection.get("availability")
        not in {"current", "unavailable"}
        or not isinstance(projection.get("complete"), bool)
        or not isinstance(items, list)
        or _parsed_timestamp(projection.get("checked_at")) is None
    ):
        return False
    if incident_kind == "security":
        if projection.get("authority") != "owner-local-security-incidents":
            return False
        id_field = "security_incident_id"
        for item in items:
            if (
                not isinstance(item, dict)
                or set(item) != SECURITY_INCIDENT_ITEM_FIELDS
                or not isinstance(item.get("occurrences"), list)
                or not all(
                    isinstance(value, dict)
                    and set(value) == SECURITY_INCIDENT_OCCURRENCE_FIELDS
                    for value in item["occurrences"]
                )
                or not isinstance(item.get("restricted_evidence_refs"), list)
                or (
                    item.get("closure_evidence") is not None
                    and (
                        not isinstance(item["closure_evidence"], dict)
                        or set(item["closure_evidence"])
                        != SECURITY_INCIDENT_CLOSURE_FIELDS
                    )
                )
                or not isinstance(item.get("events"), list)
                or not all(
                    isinstance(value, dict)
                    and set(value) == SECURITY_INCIDENT_EVENT_FIELDS
                    and (
                        value.get("occurrence") is None
                        or (
                            isinstance(value["occurrence"], dict)
                            and set(value["occurrence"])
                            == SECURITY_INCIDENT_OCCURRENCE_FIELDS
                        )
                    )
                    and (
                        value.get("closure") is None
                        or (
                            isinstance(value["closure"], dict)
                            and set(value["closure"])
                            == SECURITY_INCIDENT_CLOSURE_FIELDS
                        )
                    )
                    for value in item["events"]
                )
            ):
                return False
    else:
        id_field = "incident_id"
    identities = [
        str(item.get(id_field) or "")
        for item in items
        if isinstance(item, dict)
    ]
    if len(identities) != len(items) or any(not value for value in identities):
        return False
    if len(identities) != len(set(identities)):
        return False
    if complete:
        count = projection.get("count")
        unresolved = projection.get("unresolved_count")
        return (
            projection.get("availability") == "current"
            and isinstance(count, int)
            and not isinstance(count, bool)
            and count == len(items)
            and isinstance(unresolved, int)
            and not isinstance(unresolved, bool)
            and 0 <= unresolved <= count
        )
    return (
        projection.get("availability") == "unavailable"
        and projection.get("count") is None
        and projection.get("unresolved_count") is None
        and items == []
    )


def _valid_incident_relations(projection: Mapping[str, Any]) -> bool:
    required = {
        "schema_version",
        "authority",
        "availability",
        "complete",
        "checked_at",
        "active_relations",
        "relations",
        "by_operational_incident",
        "by_security_incident",
    }
    allowed = required | {"reason_code"}
    complete = projection.get("complete") is True
    checked_at = projection.get("checked_at")
    if (
        not required <= set(projection) <= allowed
        or projection.get("schema_version") != 1
        or projection.get("authority") != "owner-local-incident-relations"
        or projection.get("availability")
        != ("current" if complete else "unavailable")
        or not isinstance(projection.get("complete"), bool)
        or (
            complete
            and _parsed_timestamp(checked_at) is None
        )
        or (
            not complete
            and checked_at is not None
            and _parsed_timestamp(checked_at) is None
        )
        or not isinstance(projection.get("active_relations"), list)
        or not isinstance(projection.get("relations"), list)
        or not isinstance(projection.get("by_operational_incident"), dict)
        or not isinstance(projection.get("by_security_incident"), dict)
    ):
        return False
    if not complete:
        return (
            projection["active_relations"] == []
            and projection["relations"] == []
            and projection["by_operational_incident"] == {}
            and projection["by_security_incident"] == {}
        )
    relation_ids = [
        str(item.get("relation_id") or "")
        for item in projection["relations"]
        if isinstance(item, dict)
    ]
    return (
        len(relation_ids) == len(projection["relations"])
        and all(relation_ids)
        and len(relation_ids) == len(set(relation_ids))
    )


def _valid_governance_supplements(
    projection: object,
    *,
    project_logs: list[dict[str, Any]],
    source_revision: str,
) -> bool:
    if (
        not isinstance(projection, dict)
        or set(projection) != GOVERNANCE_SUPPLEMENT_PROJECTION_FIELDS
        or projection.get("schema_version") != 1
        or projection.get("source_revision") != source_revision
        or _parsed_timestamp(projection.get("checked_at")) is None
        or not isinstance(projection.get("public_log_sha256"), str)
        or not re.fullmatch(
            r"sha256:[0-9a-f]{64}",
            projection["public_log_sha256"],
        )
        or not isinstance(projection.get("items"), list)
    ):
        return False
    if projection.get("complete") is not True:
        return bool(
            projection.get("availability") == "unavailable"
            and projection.get("items") == []
            and isinstance(projection.get("reason_code"), str)
            and projection.get("reason_code")
        )
    if (
        projection.get("availability") != "current"
        or projection.get("reason_code") is not None
    ):
        return False
    governance_log = next(
        (
            log
            for log in project_logs
            if isinstance(log, dict)
            and log.get("id") == "governance-changes"
        ),
        None,
    )
    if not isinstance(governance_log, dict):
        return False
    entries = governance_log.get("entries")
    if not isinstance(entries, list):
        return False
    public_entries = {
        str(entry.get("id") or ""): entry
        for entry in entries
        if isinstance(entry, dict)
    }
    required = {
        identifier
        for identifier, entry in public_entries.items()
        if isinstance(entry.get("values"), dict)
        and entry["values"].get("supplement") == "Required"
    }
    observed: set[str] = set()
    for item in projection["items"]:
        if (
            not isinstance(item, dict)
            or set(item) != GOVERNANCE_SUPPLEMENT_ITEM_FIELDS
            or item.get("source_revision") != source_revision
            or _parsed_timestamp(item.get("recorded_at")) is None
            or not isinstance(item.get("safe_summary"), str)
            or not item["safe_summary"].strip()
        ):
            return False
        identifier = str(item.get("governance_change_id") or "")
        entry = public_entries.get(identifier)
        if (
            identifier in observed
            or not isinstance(entry, dict)
            or not isinstance(entry.get("values"), dict)
            or item.get("public_entry_sha256")
            != entry["values"].get("entry_sha256")
        ):
            return False
        observed.add(identifier)
    return observed == required


def _validate_private_operations(
    payload: Mapping[str, Any],
    *,
    generation_id: str,
    source_revision: str,
) -> tuple[str, bool]:
    action_snapshot = payload.get("action_snapshot")
    queue_directory = payload.get("queue_directory")
    operational_incidents = payload.get("operational_incidents")
    security_incidents = payload.get("security_incidents")
    incident_relations = payload.get("incident_relations")
    governance_change_supplements = payload.get(
        "governance_change_supplements"
    )
    if (
        set(payload) != PRIVATE_OPERATIONS_FIELDS
        or payload.get("schema_version") != 4
        or payload.get("availability") != "current"
        or payload.get("catalog_generation_id") != generation_id
        or payload.get("source_revision") != source_revision
        or _parsed_timestamp(payload.get("generated_at")) is None
        or not isinstance(payload.get("agent_registry"), list)
        or not isinstance(payload.get("project_logs"), list)
        or not isinstance(payload.get("integrity"), dict)
        or not isinstance(payload.get("run_chain"), dict)
        or not isinstance(action_snapshot, dict)
        or not _valid_action_snapshot(action_snapshot)
        or not isinstance(queue_directory, dict)
        or not _valid_queue_directory(queue_directory)
        or not isinstance(operational_incidents, dict)
        or not _valid_incident_projection(
            operational_incidents,
            incident_kind="operational",
        )
        or not isinstance(security_incidents, dict)
        or not _valid_incident_projection(
            security_incidents,
            incident_kind="security",
        )
        or not isinstance(incident_relations, dict)
        or not _valid_incident_relations(incident_relations)
        or not _valid_governance_supplements(
            governance_change_supplements,
            project_logs=payload["project_logs"],
            source_revision=source_revision,
        )
    ):
        raise OwnerConsoleBuildError(
            "private Operations projection is stale, incomplete, or unbound"
        )
    complete = all(
        component.get("complete") is True
        for component in (
            action_snapshot,
            queue_directory,
            operational_incidents,
            security_incidents,
            incident_relations,
            governance_change_supplements,
        )
    )
    return ("current", True) if complete else ("partial", False)


def _validate_local_status(
    payload: Mapping[str, Any],
    *,
    repository_root: Path,
) -> tuple[str, bool]:
    if (
        set(payload) != LOCAL_STATUS_FIELDS
        or payload.get("schema_version") != "1.0"
        or str(payload.get("status") or "").lower() not in STATUS_VALUES
        or payload.get("control_state") not in {"run", "paused", "unavailable"}
        or _parsed_timestamp(payload.get("control_state_checked_at")) is None
        or payload.get("canonical_path") != str(repository_root)
        or _parsed_timestamp(
            payload.get("updated_at")
            or payload.get("completed_at")
            or payload.get("started_at")
        )
        is None
        or not isinstance(payload.get("preserved_paths"), list)
    ):
        raise OwnerConsoleBuildError(
            "local automation status is malformed or bound to another checkout"
        )
    return "current", True


def _serialize_assignment(global_name: str, value: Mapping[str, Any]) -> bytes:
    serialized = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).replace("</", "<\\/")
    return (
        "/* Generated owner-only Console snapshot; never commit or publish. */\n"
        f"{global_name}={serialized};\n"
    ).encode("utf-8")


def _secure_directory(path: Path) -> None:
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        path.mkdir(mode=0o700)
        metadata = path.lstat()
    if (
        stat.S_ISLNK(metadata.st_mode)
        or not stat.S_ISDIR(metadata.st_mode)
        or metadata.st_uid != os.getuid()
        or stat.S_IMODE(metadata.st_mode) & 0o077
    ):
        raise OwnerConsoleBuildError(
            "owner Console destination is not a safe owner-only directory"
        )
    os.chmod(path, 0o700)


def _write_new_file(path: Path, content: bytes) -> None:
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags, 0o600)
    except OSError as error:
        raise OwnerConsoleBuildError(
            f"owner Console destination already exists or is unsafe: {path.name}"
        ) from error
    try:
        os.fchmod(descriptor, 0o600)
        view = memoryview(content)
        while view:
            written = os.write(descriptor, view)
            view = view[written:]
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _injected_index(source: bytes) -> bytes:
    try:
        text = source.decode("utf-8")
    except UnicodeError as error:
        raise OwnerConsoleBuildError(
            "public Console index is not valid UTF-8"
        ) from error
    pattern = re.compile(
        r'(?P<script><script\s+src="app\.js(?:\?[^"]*)?"\s*></script>)'
    )
    matches = list(pattern.finditer(text))
    if len(matches) != 1 or OWNER_BINDING_FILE in text:
        raise OwnerConsoleBuildError(
            "public Console index has an unsupported script layout"
        )
    replacement = (
        f'<script src="{OWNER_BINDING_FILE}"></script>\n'
        r"\g<script>"
    )
    return pattern.sub(replacement, text, count=1).encode("utf-8")


def build_owner_console(
    *,
    authority_descriptor: Path,
    now: datetime | None = None,
) -> Path:
    """Build and return one immutable owner-only Console version directory."""

    authority = PrivateProjectAuthority.staging(authority_descriptor)
    repository_root = Path(APPROVED_REPOSITORY_ROOT)
    try:
        repository_metadata = repository_root.lstat()
        resolved_repository = repository_root.resolve(strict=True)
    except OSError as error:
        raise OwnerConsoleBuildError(
            "approved repository root is unavailable"
        ) from error
    if (
        stat.S_ISLNK(repository_metadata.st_mode)
        or not stat.S_ISDIR(repository_metadata.st_mode)
        or resolved_repository != repository_root
    ):
        raise OwnerConsoleBuildError(
            "approved repository root is not canonical"
        )
    console_source = repository_root / PUBLIC_CONSOLE_RELATIVE
    data_source = console_source / "data"
    manifest_content = _read_regular(
        data_source / "generation-manifest.json",
        owner_only=False,
    )
    try:
        manifest = json.loads(manifest_content.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError) as error:
        raise OwnerConsoleBuildError(
            "public Console generation manifest is invalid"
        ) from error
    if not isinstance(manifest, dict):
        raise OwnerConsoleBuildError(
            "public Console generation manifest must be an object"
        )
    generation_id, source_revision, domain_contents = _validate_manifest(
        manifest,
        data_dir=data_source,
    )
    shell_contents = {
        name: _read_regular(console_source / name, owner_only=False)
        for name in PUBLIC_SHELL_FILES
    }
    catalog = _validate_catalog(
        shell_contents["catalog-data.js"],
        manifest=manifest,
        generation_id=generation_id,
        source_revision=source_revision,
    )
    staged_at = now or _utc_now()
    if staged_at.tzinfo is None:
        raise OwnerConsoleBuildError(
            "owner Console staging time must be timezone-aware"
        )
    staged_at_text = _iso_utc(staged_at)
    version_id = f"{generation_id}-{_version_timestamp(staged_at)}"
    if not GENERATION_ID_PATTERN.fullmatch(version_id):
        raise OwnerConsoleBuildError(
            "owner Console version identity is unsafe"
        )

    projection_payloads: dict[str, dict[str, Any]] = {}
    binding_projections: dict[str, dict[str, Any]] = {}
    for feed_id, (filename, prefix, comment) in PRIVATE_PROJECTION_SPECS.items():
        source_content = _read_regular(
            data_source / filename,
            owner_only=True,
        )
        payload = _json_script_payload(
            source_content,
            prefix=prefix,
            leading_comment=comment,
        )
        if feed_id == "security-assurance":
            availability, complete = _validate_security(
                payload,
                catalog=catalog,
            )
        elif feed_id == "private-operations":
            availability, complete = _validate_private_operations(
                payload,
                generation_id=generation_id,
                source_revision=source_revision,
            )
        else:
            availability, complete = _validate_local_status(
                payload,
                repository_root=repository_root,
            )
        source_hash = _sha256(source_content)
        envelope = {
            "schema_version": 1,
            "feed_id": feed_id,
            "generation_id": generation_id,
            "source_revision": source_revision,
            "source_sha256": source_hash,
            "availability": availability,
            "complete": complete,
            "staged_at": staged_at_text,
        }
        projection_payloads[filename] = {
            "owner_console_envelope": envelope,
            "payload": payload,
        }
        binding_projections[feed_id] = {
            "feed_id": feed_id,
            "relative_path": f"data/{filename}",
            "source_sha256": source_hash,
            "availability": availability,
            "complete": complete,
        }

    versions_root = authority.owner_console_versions_root
    final_root = versions_root / version_id
    temporary_root = versions_root / f".staging-{version_id}"
    exact_index_path = str(final_root / "index.html")
    binding = {
        "schema_version": 1,
        "version_id": version_id,
        "exact_decoded_file_path": exact_index_path,
        "generation_id": generation_id,
        "source_revision": source_revision,
        "staged_at": staged_at_text,
        "projections": binding_projections,
    }
    binding_content = _serialize_assignment(OWNER_BINDING_GLOBAL, binding)
    normalized_private = {
        filename: _serialize_assignment(
            PRIVATE_GLOBALS[feed_id],
            projection_payloads[filename],
        )
        for feed_id, (filename, _prefix, _comment) in PRIVATE_PROJECTION_SPECS.items()
    }
    for filename, content in normalized_private.items():
        findings = prohibited_secret_findings(
            f"owner-console/{version_id}/data/{filename}",
            content,
        )
        if findings:
            raise OwnerConsoleBuildError(
                "owner Console projection contains prohibited secret material "
                "and was not staged"
            )

    output_shell = {
        **shell_contents,
        "index.html": _injected_index(shell_contents["index.html"]),
        OWNER_BINDING_FILE: binding_content,
    }
    _secure_directory(versions_root)
    if final_root.exists() or final_root.is_symlink():
        raise OwnerConsoleBuildError(
            "owner Console version already exists; immutable versions are never overwritten"
        )
    if temporary_root.exists() or temporary_root.is_symlink():
        raise OwnerConsoleBuildError(
            "owner Console staging identity already exists"
        )
    _secure_directory(temporary_root)
    data_target = temporary_root / "data"
    _secure_directory(data_target)
    for filename, content in output_shell.items():
        _write_new_file(temporary_root / filename, content)
    _write_new_file(data_target / "generation-manifest.json", manifest_content)
    for filename, content in sorted(domain_contents.items()):
        _write_new_file(data_target / filename, content)
    for filename, content in sorted(normalized_private.items()):
        _write_new_file(data_target / filename, content)

    os.rename(temporary_root, final_root)
    return final_root


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--private-authority-descriptor",
        type=Path,
        required=True,
        help=(
            "Owner-only inactive staging descriptor. It identifies the "
            "destination but never authorizes runtime activation."
        ),
    )
    args = parser.parse_args()
    version = build_owner_console(
        authority_descriptor=args.private_authority_descriptor
    )
    print(
        json.dumps(
            {
                "status": "staged",
                "version_id": version.name,
                "entrypoint": "index.html",
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
